### ISSUE TITLE
[bug] 5.9.0 crashes on startup

### ISSUE THREAD

**Issue by ProjectPatatoe** [zwave-js/zwave-js-ui#1851]
### Version

**Checklist:**

- [x] I am **not** using Home Assistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog and my problem is **not** mentioned there.

Build/Run method

- [ ] Docker
- [x] PKG (if this means the zip?)
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

Zwavejs2Mqtt version: 5.9.0 zip from github release
Z-Wave JS version: ?

### Describe the bug

it fails immediately upon starting. rolling back to 5.8.0 works as expected
```
$ ./zwavejs2mqtt
pkg/prelude/bootstrap.js:1740
      throw error;
      ^

TypeError: Cannot read property '1' of null
    at process.dlopen (pkg/prelude/bootstrap.js:2071:69)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at Module.require (pkg/prelude/bootstrap.js:1719:31)
    at require (internal/modules/cjs/helpers.js:92:18)
    at bindings (/snapshot/zwavejs2mqtt/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/snapshot/zwavejs2mqtt/node_modules/@serialport/bindings/lib/linux.js:2:36)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22)
```
### To Reproduce

unzip  https://github.com/zwave-js/zwavejs2mqtt/releases/download/v5.9.0/zwavejs2mqtt-v5.9.0.zip
./zwavejs2mqtt
get error

**Comment by robertsLando** [comment]
Let me know and if needed open a new issue
