### ISSUE TITLE
Migrated from Z-Stick 7 to Z-stick 5 (non +) - Issues with checking firmware

### ISSUE THREAD

**Issue by Hooverjc** [zwave-js/zwave-js-ui#2938]
I finally had enough with dealing with all the dead nodes and performance issues related to my z-stick 7 and performed an NVM backup and restore to a Z-stick 5. All is working much better now, but I've noted in the logs that i'm getting an error on most of my devices at boot and if I manually try to check for firmware updates.  When I manually check for an update, I see this error  in the UI and log:

2023-02-01 10:06:51.505 INFO Z-WAVE: Cannot check for firmware updates for node 58: Cannot read properties of undefined (reading 'includes') (ZW0261) getAvailableFirmwareUpdates undefined

when I reboot, I see the following error for every node:

2023-02-01 10:09:06.359 ERROR Z-WAVE-SERVER: Cannot check for firmware updates for node 24: Cannot read properties of undefined (reading 'includes') (ZW0261)
ZWaveError: Cannot check for firmware updates for node 24: Cannot read properties of undefined (reading 'includes') (ZW0261)
    at ZWaveController.getAvailableFirmwareUpdates (/usr/src/app/node_modules/zwave-js/src/lib/controller/Controller.ts:5234:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Function.handle (/usr/src/app/node_modules/@zwave-js/server/dist/lib/controller/message_handler.js:205:30)
    at Client.receiveMessage (/usr/src/app/node_modules/@zwave-js/server/dist/lib/server.js:106:62)

I've attempted to re-interview the nodes, refresh values, heal them, update topics, but none of these appear to resolve this issue. Is this expected behavior on a 500 series device (maybe unhandled due to my swap) or is there an issue going on here? I can only find one reference to this error online, so trying to get some more information on what else may be wrong.

Thanks!

**Comment by crawford** [comment]
I'm also seeing these errors in my setup (zwave-js-ui 1.6.2, Home Assistant 2023.1.4).

I see this error message in the UI when checking for firmware updates: `Error while calling api getAvailableFirmwareUpdates: Cannot check for firmware updates for node 6: Cannot read properties of undefined (reading 'includes') (ZW0261)`.

And this is what I see in the debug window (@Hooverjc how did you get stack traces in your logs?) :

```
2023-01-31 08:50:43.266 INFO Z-WAVE: Calling api getAvailableFirmwareUpdates with args: [ 23, { includePrereleases: false }, [length]: 2 ]
2023-01-31 08:50:43.758 INFO Z-WAVE: Cannot check for firmware updates for node 23: Cannot read properties of undefined (reading 'includes') (ZW0261) getAvailableFirmwareUpdates undefined
2023-01-31 08:50:53.331 INFO Z-WAVE: Calling api getAvailableFirmwareUpdates with args: [ 23, { includePrereleases: true }, [length]: 2 ]
2023-01-31 08:50:53.821 INFO Z-WAVE: Cannot check for firmware updates for node 23: Cannot read properties of undefined (reading 'includes') (ZW0261) getAvailableFirmwareUpdates undefined
2023-01-31 08:51:02.553 INFO Z-WAVE: Calling api getAvailableFirmwareUpdates with args: [ 23, { includePrereleases: false }, [length]: 2 ]
2023-01-31 08:51:03.063 INFO Z-WAVE: Cannot check for firmware updates for node 23: Cannot read properties of undefined (reading 'includes') (ZW0261) getAvailableFirmwareUpdates undefined
```

**Comment by Hooverjc** [comment]
> And this is what I see in the debug window (@Hooverjc how did you get stack traces in your logs?) :

I have logging enabled at the log level of "error" and this is just how it reports for me in the docker logs. Again, the more verbose message is only present at boot, the manual check looks similar to yours, I just had a hard time getting both lines together due to activity at home causing lots of traffic on the network.

**Comment by thenoid** [comment]
Ditto - my logs look identical.

**Comment by robertsLando** [comment]
> 2023-01-31 08:50:43.758 INFO Z-WAVE: Cannot check for firmware updates for node 23: Cannot read properties of undefined (reading 'includes') (ZW0261) getAvailableFirmwareUpdates undefined

I think this is an issue on your side @AlCalzone
