### ISSUE TITLE
Debug logs show 404 for /apple-touch-icon-precomposed.png

### ISSUE THREAD

**Issue by jamespreedy** [zwave-js/zwave-js-ui#2957]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.8.5.2d9d59c

### ZwaveJS version

10.10.0

### Describe the bug

In the debug logs, when opening that pane, I see the below 404 request.

```
2023-02-11 16:06:28.019 INFO APP: GET /apple-touch-icon-precomposed.png 404 5.021 ms - 1058
Error: Not Found
at /usr/src/app/server/app.js:1096:17
at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
at /usr/src/app/node_modules/express/lib/router/index.js:286:9
at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
at session (/usr/src/app/node_modules/express-session/index.js:479:7)
at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
at /usr/src/app/node_modules/express/lib/router/index.js:286:9
2023-02-11 16:06:28.027 INFO APP: GET /apple-touch-icon.png 404 9.437 ms - 1058
2023-02-11 16:06:28.031 INFO APP: GET /favicon.ico 404 13.128 ms - 1058
Error: Not Found
at /usr/src/app/server/app.js:1096:17
at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
at /usr/src/app/node_modules/express/lib/router/index.js:286:9
at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
at session (/usr/src/app/node_modules/express-session/index.js:479:7)
at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
at /usr/src/app/node_modules/express/lib/router/index.js:286:9
Error: Not Found
at /usr/src/app/server/app.js:1096:17
at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
at /usr/src/app/node_modules/express/lib/router/index.js:286:9
at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:346:12)
at next (/usr/src/app/node_modules/express/lib/router/index.js:280:10)
at session (/usr/src/app/node_modules/express-session/index.js:479:7)
at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:328:13)
at /usr/src/app/node_modules/express/lib/router/index.js:286:9
2023-02-11 16:06:28.074 INFO APP: GET /static/favicons/favicon-16x16.png 200 6.192 ms - 1137
2023-02-11 16:06:28.076 INFO APP: GET /static/favicons/favicon-32x32.png 200 7.794 ms - 1670
2023-02-11 16:06:28.079 INFO APP: GET /static/favicons/apple-touch-icon.png 200 8.923 ms - 3416
2023-02-11 16:06:28.095 INFO APP: GET /debug 304 3.989 ms - -
2023-02-11 16:06:28.104 INFO APP: GET /static/favicons/site.webmanifest 304 2.036 ms - -
2023-02-11 16:06:28.108 INFO APP: GET /static/css/app.9f4195d78b467ea53e93.css 304 4.362 ms - -
2023-02-11 16:06:28.110 INFO APP: GET /static/js/app.0163631f057799784035.js 304 3.119 ms - -
2023-02-11 16:06:28.171 INFO APP: GET /api/auth-enabled 304 2.095 ms - -
2023-02-11 16:06:28.194 INFO APP: GET /static/logo.png 304 1.159 ms - -
2023-02-11 16:06:28.241 INFO APP: GET //static/fonts/MaterialIcons-Regular.2d80174.woff2 304 9.512 ms - -
2023-02-11 16:06:28.364 INFO APP: GET /api/settings 304 154.728 ms - -
2023-02-11 16:06:28.404 INFO APP: GET /api/auth-enabled 304 2.510 ms - -
2023-02-11 16:07:02.287 INFO Z-WAVE: [Node 008] Metadata updated: 49-0-Air temperature
2023-02-11 16:07:02.294 INFO Z-WAVE: [Node 008] Value updated: 49-0-Air temperature 19.3 => 19
```

### To Reproduce

Go to the URL for zwave-js-ui.
Click debug from the side menu.
Click open in window.
Observe logs.

### Expected behavior

The 404 missing images are unexpected.

### Additional context

Please let me know if you have any questions, or if I can provide different logs etc.
Very happy to help.

**Comment by robertsLando** [comment]
I'm not able to reproduce this, does this happens when you open the web page with an iOS device? Which one specifically?

**Comment by jamespreedy** [comment]
Hi @robertsLando - thanks for your help.

Yes correct, doesn't happen when I open it from my iPhone.
Only happens when I open it from my Mac - I have an Apple Silicon M2 MacBook Air (Mac14,2).

**Comment by robertsLando** [comment]
I think Mac requires some special icons that are not provided by default, anyway nothing that should break anything but I keep this open until I find some time to look at it
