### ISSUE TITLE
zwave js ui container upgrade from 10.10.0 to 10.11.0 results in continuous container reboot.

### ISSUE THREAD

**Issue by ChrisCaho** [zwave-js/zwave-js-ui#2994]
zwave js ui container upgrade from 10.10.0 to 10.11.0 results in continuous container reboot.

I backed the container down to 10.10.0 and it is running fine.  

Here is the log for 10.11.0.  Any idea what is going on?

-----------------
2023-03-08 16:05:39.098 INFO APP: Version: 8.10.0.8737258
2023-03-08 16:05:39.105 INFO APP: Application path:/usr/src/app
  ______  __          __                      _  _____     _    _ _____
 |___  /  \ \        / /                     | |/ ____|   | |  | |_   _|
    / /____\ \  /\  / /_ ___   _____         | | (___     | |  | | | |
   / /______\ \/  \/ / _' \ \ / / _ \    _   | |\___ \    | |  | | | |
  / /__      \  /\  / (_| |\ V /  __/   | |__| |____) |   | |__| |_| |_
 /_____|      \/  \/ \__,_| \_/ \___|    \____/|_____/     \____/|_____|
2023-03-08 16:05:39.265 INFO MQTT: Connecting to mqtt://master.chriscaho.com:1883
2023-03-08 16:05:39.422 INFO BACKUP: Backup job started with cron: 0 0 * * *. Next run: 3/9/2023, 12:00:00 AM
2023-03-08 16:05:39.423 WARN BACKUP: Nvm backup is disabled
2023-03-08 16:05:39.459 INFO Z-WAVE: Connecting to /dev/ttyACM0
2023-03-08T22:05:39.462Z DRIVER   ███████╗ ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗             ██╗ ███████╗
                                  ╚══███╔╝ ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝             ██║ ██╔════╝
                                    ███╔╝  ██║ █╗ ██║ ███████║ ██║   ██║ █████╗   █████╗      ██║ ███████╗
                                   ███╔╝   ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝   ╚════╝ ██   ██║ ╚════██║
                                  ███████╗ ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗        ╚█████╔╝ ███████║
                                  ╚══════╝  ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝         ╚════╝  ╚══════╝
2023-03-08T22:05:39.465Z DRIVER   version 10.11.0
2023-03-08T22:05:39.465Z DRIVER
2023-03-08 16:05:39.522 INFO Z-WAVE: Zwavejs usage statistics ENABLED
2023-03-08 16:05:39.523 WARN Z-WAVE: Zwavejs driver is not ready yet, statistics will be enabled on driver initialization
    at Socket.emit (node:events:525:35)
    at Socket.emit (node:domain:489:12)
    at Socket.emitUntyped (/usr/src/app/node_modules/socket.io/dist/typed-events.js:69:22)
    at /usr/src/app/node_modules/socket.io/dist/socket.js:703:39
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
-----------------

Working version.....

2023-03-08 16:07:47.498 INFO APP: Version: 8.9.0.2d95700
2023-03-08 16:07:47.505 INFO APP: Application path:/usr/src/app
  ______  __          __                      _  _____     _    _ _____
 |___  /  \ \        / /                     | |/ ____|   | |  | |_   _|
    / /____\ \  /\  / /_ ___   _____         | | (___     | |  | | | |
   / /______\ \/  \/ / _' \ \ / / _ \    _   | |\___ \    | |  | | | |
  / /__      \  /\  / (_| |\ V /  __/   | |__| |____) |   | |__| |_| |_
 /_____|      \/  \/ \__,_| \_/ \___|    \____/|_____/     \____/|_____|

2023-03-08 16:07:47.579 INFO APP: Listening on port 8091 host 0.0.0.0 protocol HTTP
2023-03-08 16:07:47.659 INFO MQTT: Connecting to mqtt://master.chriscaho.com:1883
2023-03-08 16:07:47.817 INFO BACKUP: Backup job started with cron: 0 0 * * *. Next run: 3/9/2023, 12:00:00 AM
2023-03-08 16:07:47.818 WARN BACKUP: Nvm backup is disabled
2023-03-08 16:07:47.853 INFO Z-WAVE: Connecting to /dev/ttyACM0
2023-03-08T22:07:47.856Z DRIVER   ███████╗ ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗             ██╗ ███████╗
                                  ╚══███╔╝ ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝             ██║ ██╔════╝
                                    ███╔╝  ██║ █╗ ██║ ███████║ ██║   ██║ █████╗   █████╗      ██║ ███████╗
                                   ███╔╝   ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝   ╚════╝ ██   ██║ ╚════██║
                                  ███████╗ ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗        ╚█████╔╝ ███████║
                                  ╚══════╝  ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝         ╚════╝  ╚══════╝
2023-03-08T22:07:47.858Z DRIVER   version 10.10.0
2023-03-08T22:07:47.859Z DRIVER
2023-03-08 16:07:47.915 INFO Z-WAVE: Zwavejs usage statistics ENABLED
2023-03-08 16:07:47.916 WARN Z-WAVE: Zwavejs driver is not ready yet, statistics will be enabled on driver initialization
2023-03-08T22:07:52.146Z CONFIG   version 10.10.0
2023-03-08T22:07:54.484Z DRIVER   Dropping message because the driver is not ready to handle it yet.
2023-03-08T22:07:54.545Z DRIVER   Dropping message because the driver is not ready to handle it yet.
2023-03-08T22:07:54.565Z DRIVER   Dropping message because the driver is not ready to handle it yet.
2023-03-08T22:08:02.020Z CNTRLR   querying controller IDs...
2023-03-08T22:08:02.328Z CNTRLR   received controller IDs:
                                    home ID:     0xf1762680
                                    own node ID: 1
2023-03-08T22:08:02.330Z CNTRLR   querying API capabilities...
2023-03-08T22:08:02.360Z CNTRLR   received API capabilities:
                                    firmware version:    2.3
                                    manufacturer ID:     0x027a
                                    product type:        0x0401
                                    product ID:          0x02
                                    supported functions:
                                    · GetSerialApiInitData (0x02)
                                    · SetApplicationNodeInformation (0x03)
                                    · ApplicationCommand (0x04)
                                    · GetControllerCapabilities (0x05)
                                    · SetSerialApiTimeouts (0x06)
                                    · GetProtocolVersion (0x09)
                                    · SerialAPIStarted (0x0a)
                                    · SerialAPISetup (0x0b)
                                    · SetRFReceiveMode (0x10)
                                    · UNKNOWN_FUNC_SET_SLEEP_MODE (0x11)
                                    · FUNC_ID_ZW_SEND_NODE_INFORMATION (0x12)
                                    · SendData (0x13)
                                    · SendDataMulticast (0x14)
                                    · GetControllerVersion (0x15)
                                    · SendDataAbort (0x16)
                                    · FUNC_ID_ZW_R_F_POWER_LEVEL_SET (0x17)
                                    · FUNC_ID_ZW_GET_RANDOM (0x1c)
                                    · GetControllerId (0x20)
                                    · UNKNOWN_FUNC_MEMORY_GET_BYTE (0x21)
                                    · UNKNOWN_FUNC_MEMORY_PUT_BYTE (0x22)
                                    · UNKNOWN_FUNC_MEMORY_GET_BUFFER (0x23)
                                    · UNKNOWN_FUNC_MEMORY_PUT_BUFFER (0x24)
                                    · EnterBootloader (0x27)
                                    · UNKNOWN_FUNC_UNKNOWN_0x28 (0x28)
                                    · GetNVMId (0x29)
                                    · ExtNVMReadLongBuffer (0x2a)
                                    · ExtNVMWriteLongBuffer (0x2b)
                                    · ExtNVMReadLongByte (0x2c)
                                    · ExtExtWriteLongByte (0x2d)
                                    · NVMOperations (0x2e)
                                    · undefined (0x2f)
                                    · undefined (0x37)
                                    · undefined (0x38)
                                    · UNKNOWN_FUNC_ClearNetworkStats (0x39)
                                    · UNKNOWN_FUNC_GetNetworkStats (0x3a)
                                    · GetBackgroundRSSI (0x3b)
                                    · undefined (0x3c)
                                    · UNKNOWN_FUNC_RemoveNodeIdFromNetwork (0x3f)
                                    · GetNodeProtocolInfo (0x41)
                                    · HardReset (0x42)
                                    · FUNC_ID_ZW_REPLICATION_COMMAND_COMPLETE (0x44)
                                    · FUNC_ID_ZW_REPLICATION_SEND_DATA (0x45)
                                    · AssignReturnRoute (0x46)
                                    · DeleteReturnRoute (0x47)
                                    · RequestNodeNeighborUpdate (0x48)
                                    · ApplicationUpdateRequest (0x49)
                                    · AddNodeToNetwork (0x4a)
                                    · RemoveNodeFromNetwork (0x4b)
                                    · FUNC_ID_ZW_CREATE_NEW_PRIMARY (0x4c)
                                    · FUNC_ID_ZW_CONTROLLER_CHANGE (0x4d)
                                    · AssignPriorityReturnRoute (0x4f)
                                    · FUNC_ID_ZW_SET_LEARN_MODE (0x50)
                                    · AssignSUCReturnRoute (0x51)
                                    · FUNC_ID_ZW_REQUEST_NETWORK_UPDATE (0x53)
                                    · SetSUCNodeId (0x54)
                                    · DeleteSUCReturnRoute (0x55)
                                    · GetSUCNodeId (0x56)
                                    · UNKNOWN_FUNC_SEND_SUC_ID (0x57)
                                    · AssignPrioritySUCReturnRoute (0x58)
                                    · FUNC_ID_ZW_EXPLORE_REQUEST_INCLUSION (0x5e)
                                    · undefined (0x5f)
                                    · RequestNodeInfo (0x60)
                                    · RemoveFailedNode (0x61)
                                    · IsFailedNode (0x62)
                                    · ReplaceFailedNode (0x63)
                                    · UNKNOWN_FUNC_UNKNOWN_0x66 (0x66)
                                    · UNKNOWN_FUNC_UNKNOWN_0x67 (0x67)
                                    · FirmwareUpdateNVM (0x78)
                                    · GetRoutingInfo (0x80)
                                    · UNKNOWN_FUNC_LOCK_ROUTE_RESPONSE (0x90)
                                    · GetPriorityRoute (0x92)
                                    · SetPriorityRoute (0x93)
                                    · UNKNOWN_FUNC_UNKNOWN_0xB4 (0xb4)
                                    · UNKNOWN_FUNC_WATCH_DOG_ENABLE (0xb6)
                                    · UNKNOWN_FUNC_WATCH_DOG_DISABLE (0xb7)
                                    · UNKNOWN_FUNC_WATCH_DOG_KICK (0xb8)
                                    · UNKNOWN_FUNC_UNKNOWN_0xB9 (0xb9)
                                    · UNKNOWN_FUNC_RF_POWERLEVEL_GET (0xba)
                                    · UNKNOWN_FUNC_GET_LIBRARY_TYPE (0xbd)
                                    · UNKNOWN_FUNC_SEND_TEST_FRAME (0xbe)
                                    · FUNC_ID_PROMISCUOUS_APPLICATION_COMMAND_HANDLER (0xd1)
                                    · UNKNOWN_FUNC_UNKNOWN_0xD2 (0xd2)
                                    · UNKNOWN_FUNC_UNKNOWN_0xD3 (0xd3)
                                    · UNKNOWN_FUNC_UNKNOWN_0xD4 (0xd4)
                                    · undefined (0xee)
                                    · UNKNOWN_FUNC_UNKNOWN_0xEF (0xef)
2023-03-08T22:08:02.415Z CNTRLR   Performing soft reset...
2023-03-08T22:08:02.439Z CNTRLR   Waiting for the controller to reconnect...
2023-03-08T22:08:03.942Z CNTRLR   Re-opening serial port...
2023-03-08T22:08:04.953Z CNTRLR   Waiting for the Serial API to start...
2023-03-08T22:08:05.671Z CNTRLR   received version info:
                                    controller type: Static Controller
                                    library version: Z-Wave 6.04
2023-03-08T22:08:05.673Z CNTRLR   querying protocol version info...
2023-03-08T22:08:05.712Z CNTRLR   received protocol version info:
                                    protocol type:             Z-Wave
                                    protocol version:          6.4.0
                                    appl. framework build no.: 91
2023-03-08T22:08:05.716Z CNTRLR   supported Z-Wave features:
                                    · SmartStart
2023-03-08T22:08:05.717Z CNTRLR   querying controller capabilities...
2023-03-08T22:08:05.745Z CNTRLR   received controller capabilities:
                                    controller role:      primary
                                    is the SUC:           true
                                    started this network: true
                                    SIS is present:       true
                                    was real primary:     true
2023-03-08T22:08:05.746Z CNTRLR   querying serial API setup capabilities...
2023-03-08T22:08:05.764Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2023-03-08T22:08:05.769Z CNTRLR   [Node 006] is unknown - discarding received command...
2023-03-08T22:08:05.804Z CNTRLR   [Node 006] is unknown - discarding received command...
2023-03-08T22:08:05.882Z CNTRLR   supported serial API setup commands:
                                  · GetSupportedCommands
                                  · SetTxStatusReport
                                  · SetPowerlevel
                                  · GetPowerlevel
                                  · GetMaximumPayloadSize
2023-03-08T22:08:05.883Z CNTRLR   Enabling TX status report...
2023-03-08T22:08:05.904Z CNTRLR   Enabling TX status report successful...
2023-03-08T22:08:05.905Z CNTRLR   finding SUC...
2023-03-08T22:08:05.928Z CNTRLR   This is the SUC
2023-03-08T22:08:05.929Z CNTRLR   querying additional controller information...
2023-03-08T22:08:06.054Z CNTRLR   received additional controller information:
                                    Z-Wave API version:         8 (legacy)
                                    Z-Wave chip type:           ZW050x
                                    node type                   Controller
                                    controller role:            primary
                                    controller is the SIS:      true
                                    controller supports timers: false
                                    nodes in the network:       1, 6, 9, 11, 17, 18, 19, 20, 21, 22, 23, 24, 25,
                                   26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 4
                                  5, 46, 47
2023-03-08T22:08:06.211Z CNTRLR   [Node 001] Embedded device config loaded

**Comment by PrplHaz4** [comment]
I am seeing the same issue.  Reverting to `zwavejs/zwave-js-ui:8.9.0` appears to have fixed it.  It looks like the issue began immediately after watchtower updated the container today.

In addition to the error below, I was getting a 500 error response on GET /health/zwave (normally 200 OK)

A relevant addition to the log above:

```
Mar 8, 2023 @ 23:32:40.248 TypeError: cb is not a function
Mar 8, 2023 @ 23:32:40.248     at Socket.<anonymous> (/usr/src/app/server/app.js:480:17)
Mar 8, 2023 @ 23:32:40.248     at Socket.emit (node:events:525:35)
Mar 8, 2023 @ 23:32:40.248     at Socket.emit (node:domain:489:12)
Mar 8, 2023 @ 23:32:40.248     at Socket.emitUntyped (/usr/src/app/node_modules/socket.io/dist/typed-events.js:69:22)
Mar 8, 2023 @ 23:32:40.248     at /usr/src/app/node_modules/socket.io/dist/socket.js:703:39
Mar 8, 2023 @ 23:32:40.248     at processTicksAndRejections (node:internal/process/task_queues:77:11)
```

**Comment by robertsLando** [comment]
Fixes on master, thanks and sorry for that 🙏🏼 Will release a patch soon

**Comment by ChrisCaho** [comment]
Just pulled new versions and starting properly.  Thanks.

**Comment by PrplHaz4** [comment]
Confirmed fixed over here too...thanks so much for the quick fix!

**Comment by robertsLando** [comment]
Thanks for the feedback 🙏🏼
