### ISSUE TITLE
Unexpected Exception

### ISSUE THREAD

**Issue by dxfoxd** [zwave-js/zwave-js-ui#3064]
### Checklist

- [x]  I am not using Home Assistant. Or: a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is not described there.
- [x] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

zwave-js-ui: 8.9.0.2d95700 

### ZwaveJS version

10.10.0

### Describe the bug

Apart from the bogus capabilities now reported (to give you an idea, the last clean install showed 51 devices with 346 capabilities, the new count of capabilities is now 612), the integration is in an error state almost daily now. The only way to enable is to completely reboot the Rpi or reset the USB port. Today I was able to discover the error in the logs, but I cannot istate with no option to reload in the GUI. 

Unexpected exeption '49-37-0-Currentvalue. 

Besides that, there are some other issues as well.
1. The integration shows 51 entities
2. There should be 51 devices including the controller, but in the zwave-js-ui only shows 49 nodes. It seems that the controller deleted 2 devices unexpectedly.

I'm blank here, don't know how to get the integration stable anymore. Every day it takes me several hours to get the system up and running gain. Is this an issue with the integration, or just a defective Z-wave controller (Aeotec Z Stick 7 fw 7.19.2)? I can provide any log but don't know how to identify this error.

Logs when this occurred:
```
2023-04-26 16:27:28.872 ERROR (MainThread) [homeassistant.components.zwave_js] Unexpected exception: '49-37-0-currentValue'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/__init__.py", line 765, in client_listen
    await client.listen(driver_ready)
  File "/usr/local/lib/python3.10/site-packages/zwave_js_server/client.py", line 261, in listen
    await self.receive_until_closed()
  File "/usr/local/lib/python3.10/site-packages/zwave_js_server/client.py", line 329, in receive_until_closed
    self._handle_incoming_message(data)
  File "/usr/local/lib/python3.10/site-packages/zwave_js_server/client.py", line 412, in _handle_incoming_message
    self.driver.receive_event(event)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/zwave_js_server/model/driver.py", line 81, in receive_event
    self.controller.receive_event(event)
  File "/usr/local/lib/python3.10/site-packages/zwave_js_server/model/controller/__init__.py", line 799, in receive_event
    node.receive_event(event)
  File "/usr/local/lib/python3.10/site-packages/zwave_js_server/model/node/__init__.py", line 404, in receive_event
    self._handle_event_protocol(event)
  File "/usr/local/lib/python3.10/site-packages/zwave_js_server/event.py", line 69, in _handle_event_protocol
    handler(event)
  File "/usr/local/lib/python3.10/site-packages/zwave_js_server/model/node/__init__.py", line 858, in handle_value_removed
    event.data["value"] = self.values.pop(value_id)
KeyError: '49-37-0-currentValue'
2023-04-26 16:27:28.878 INFO (MainThread) [homeassistant.components.zwave_js] Disconnected from server. Reloading integration
2023-04-26 16:27:33.630 WARNING (MainThread) [homeassistant.components.sensor] Updating command_line sensor took longer than the scheduled update interval 0:00:01
2023-04-26 16:27:33.634 WARNING (MainThread) [homeassistant.components.media_player] Updating dlna_dmr media_player took longer than the scheduled update interval 0:00:10
2023-04-26 16:27:33.641 INFO (MainThread) [homeassistant.components.automation.ping_dead_zwave_devices] Ping Dead ZWave Devices: Running automation actions
2023-04-26 16:27:33.642 INFO (MainThread) [homeassistant.components.automation.ping_dead_zwave_devices] Ping Dead ZWave Devices: Executing step call service
2023-04-26 16:27:33.646 WARNING (MainThread) [homeassistant.components.automation.ping_dead_zwave_devices] Ping Dead ZWave Devices: Already running
2023-04-26 16:27:34.586 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities button.btn_1_ping, button.cos_1_ping, button.cs_1_ping, button.cs_2_ping, button.cs_3_ping, button.cs_4_ping, button.cs_5_ping, button.cs_6_ping, button.dm_1_ping, button.dm_2_ping, button.md_1_ping, button.ms_1_ping, button.ms_2_ping, button.ms_3_ping, button.pir_10_ping, button.pir_1_ping, button.pir_2_ping, button.pir_3_ping, button.pir_4_ping, button.pir_5_ping, button.pir_6_ping, button.pir_7_ping, button.pir_8_ping, button.pir_9_ping, button.sir_1_ping, button.sir_2_ping, button.sir_3_ping, button.sms_1_ping, button.sms_2_ping, button.sms_3_ping, button.wp_11_ping, button.wp_12_ping, button.wp_1_ping, button.wp_2_ping, button.wp_3_ping, button.wp_4_ping, button.wp_5_ping, button.wp_6_ping, button.wp_7_ping, button.wp_9_ping, button.ws_10_ping, button.ws_12_ping, button.ws_1_ping, button.ws_2_ping, button.ws_3_ping, button.ws_4_ping, button.ws_5_ping, button.ws_7_ping, button.ws_8_ping, button.ws_9_ping or it is/they are currently not available
2023-04-26 16:27:34.592 WARNING (MainThread) [homeassistant.components.sensor] Updating command_line sensor took longer than the scheduled update interval 0:00:01
2023-04-26 16:27:34.619 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Z-Wave JS for zwave_js
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/__init__.py", line 816, in async_unload_entry
    await disconnect_client(hass, entry)
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/__init__.py", line 795, in disconnect_client
    await asyncio.gather(listen_task, start_client_task, *platform_setup_tasks)
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/__init__.py", line 212, in start_client
    await driver_events.setup(client.driver)
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/__init__.py", line 261, in setup
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/__init__.py", line 356, in async_on_node_added
    await self.node_events.async_on_node_ready(node)
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/__init__.py", line 479, in async_on_node_ready
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/__init__.py", line 480, in <genexpr>
    *(
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/discovery.py", line 862, in async_discover_node_values
    yield from async_discover_single_value(value, device, discovered_value_ids)
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/discovery.py", line 917, in async_discover_single_value
    value.node.device_class.basic, schema.device_class_basic
  File "/usr/local/lib/python3.10/site-packages/zwave_js_server/model/device_class.py", line 46, in basic
    return DeviceClassItem(**self.data["basic"])
TypeError: 'NoneType' object is not subscriptable
```

### To Reproduce

Unknown

### Expected behavior

Normal operation of zwave-js-ui and integration.

**Comment by robertsLando** [comment]
@dxfoxd Did you tried to firstly ask this to HA team? It's difficult for me to say where the problem could be without a log of zui/zwavejs driver

Please make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` and attach it here as a file (drag & drop into the text field).

Giving the log you attached here seems the problem is on HA side BTW.

cc @raman325

**Comment by dxfoxd** [comment]
Thx. Daniel. No I didn't ask this at the HA team yet. For now I tries to stabilize the network with a hard reset of the controller and restoring the NVM. That seems to work for now, but I had to pull the controller from the USB port as well . The hard reset was also necessary because the controller showed weird readings and I was not able to update these values (kept returning to the false values)
![image](https://user-images.githubusercontent.com/80631257/235008786-43054f58-6f33-46a2-9494-296dc7921759.png). I also enabled all logs now as wel in zwave-js-ui and the HA integration. Because I am travelling the next 10 days I need to rely on this and where possible will monitor HA from a distance. I will upload the logs after May 8th.
What was also bothering me is that I never can display a network graph. I only can see it like this. 
![image](https://user-images.githubusercontent.com/80631257/235009951-d94c0439-550c-4d86-9bd4-ccb962ada4d9.png)
I didn't pay too much attention to this because the network graphs function that was discussed elsewhere claimed that this never was a correct display of the connections, but now I am curious if this is also related to the issues that I have.
To be complete, I also include a screenshot of my current settings and the compose.yaml section of the zwave-js-ui docker container.
```
  zwave-js-ui:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui:latest
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=[redacted]
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      - TZ=Europe/Amsterdam
      - KEY_S2_Unauthenticated=[redacted]
      - KEY_S2_Authenticated=[redacted]
      - KEY_S2_AccessControl=[redacted]
      - KEY_S0_Legacy=[redacted]
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_e63df2d83e94eb11adbf36703d98b6d1-if00-port0:/dev/zwave
    volumes:
      - /home/pi/zwave-js-ui:/usr/src/app/store #[host folder]:[container folder]
      - /home/pi/zwave-js-ui/backups:/usr/src/app/store/backups
    ports:
      - "8091:8091" # port for web interface
      - "3000:3000" # port for Z-Wave JS websocket server
```
![screencapture-192-168-10-73-8091-settings-2023-04-28-01_07_59](https://user-images.githubusercontent.com/80631257/235010524-2bbe0933-de78-4115-a2b3-301a1e9b65bf.png)

**Comment by dxfoxd** [comment]
FYI, after a 10 days absence the app was still buggy, more than 700 device capabilities (effective appr. 330) and also the Z-wave stick could showed strange settings, the region was "unavailable"and "Measured output power at 0 dBm" showed -2352.78. Updating both settings didn't work. I now restored a previous NVM and updated HA core and the zwave-js-ui app (both running in separate Docker containers). Everything is working again and when this bug occurs again I will upload the logs.

**Comment by robertsLando** [comment]
@dxfoxd Giving the values of rf region and power I think the stick was messed up, dunno the reason.

@AlCalzone any clue what could cause this?

**Comment by dxfoxd** [comment]
Today I discovered that suddenly a node ( Node 049) was deleted, unknown what caused this. I found only 
`2023-05-12 18:47:56.818 INFO Z-WAVE: [Node 049] Removed` in z-ui-current_log. No event is found in zwavejs_current.log. Moreover, this last log seems corrupted.
[logs.zip](https://github.com/zwave-js/zwave-js-ui/files/11467929/logs.zip)
Device capabilities count was now at 738 but I was able to select and remove 66.
Z-wave network performance is very slow, command execution by devices take over 10 seconds. Is that caused by the extensive logging?
I hope you can analyse what may cause this removal.

**Comment by dxfoxd** [comment]
Today I had the "Unexpected Exception" again in HA. As a result the integration is no longer available unless HA is restarted. Logs are attached, Bug is also reported at HA core team [https://github.com/home-assistant/core/issues/93096]
[home-assistant_2023-05-15T12-07-12.866Z.log](https://github.com/zwave-js/zwave-js-ui/files/11477736/home-assistant_2023-05-15T12-07-12.866Z.log)

**Comment by AlCalzone** [comment]
Do you have any secondary controller that can perform inclusion or exclusion of devices? Because it does look like another controller is removing the device from the network.
```
2023-05-12T16:47:56.547Z DRIVER « [Node 049] [REQ] [ApplicationUpdateRequest]
                                    payload: 0x3100
2023-05-12T16:47:56.550Z CNTRLR   [Node 049] was removed from the network by another controller
```

As for the network performance, there's a huge load of traffic on the network. A handful of nodes with bad connectivity flood the network with reports every couple of milliseconds. Almost all incoming commands have an RSSI value between -89 and -100 dBm, which is extremely close to background noise levels.

Make sure to follow and apply
- this: https://zwave-js.github.io/node-zwave-js/#/troubleshooting/connectivity-issues?id=general-troubleshooting
- and this: https://zwave-js.github.io/node-zwave-js/#/troubleshooting/network-health?id=optimizing-the-reporting-configuration
- and finally this: https://zwave-js.github.io/node-zwave-js/#/troubleshooting/network-health?id=testing-the-connection-strength

**Comment by dxfoxd** [comment]
Having installed and configured the Aeotec Z-Stick Gen 5+ for several weeks now, I believe this issue is resolved. I adapted all your recommendations and I’m happy that no issues are caused by the Z-Wave integration or bogus entities are created. I don’t know if the Aeotec Z-Stick 7 (EU version) was not working properly, but I would recommend anyone to stick with the Gen 5+ version. Thx. For all your help. I will now close this issue.
