### ISSUE TITLE
Unhandled Exception, All Values Stop Getting Updated

### ISSUE THREAD

**Issue by evan-swinney** [zwave-js/zwave-js-ui#3300]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

8.23.2.882c26e

### ZwaveJS version

11.13.0

### Describe the bug

The integration works fine for hours, or even days, and then eventually it starts producing this error within the logs:
```
2023-09-26 03:05:32.287 ERROR APP: Unhandled Rejection, reason: TypeError: Cannot read properties of undefined (reading 'label')
2023-09-26 03:05:32.387 ERROR APP: Unhandled Rejection, reason: TypeError: Cannot read properties of undefined (reading 'label')
2023-09-26 03:05:38.086 ERROR APP: Unhandled Rejection, reason: TypeError: Cannot read properties of undefined (reading 'label')
2023-09-26 03:05:38.223 ERROR APP: Unhandled Rejection, reason: TypeError: Cannot read properties of undefined (reading 'label')
```

When this happens, Home Assistant cannot read any more data from the websocket and all values cease to update.

An additional side-effect of this is when it starts doing this, all of my devices which had previously had correct Manufacturer and Product names revert back to showing as Unknown.

Restarting the ZWave JS UI container does not resolve the issue. Restarting Home Assistant does not resolve the issue.

### To Reproduce

Unknown; it starts happening seemingly at random. The first time it happened within 24 hours, the second time it took 2 weeks. Home Assistant & ZWave JS UI were completely hands off during those time periods.

### Expected behavior

For errors to not show up in the logs; for data to keep streaming over the websocket connection to Home Assistant; for product and vendor names to show their correct values.

### Additional context

Everything is Dockerized & run in Kubernetes with the following Docker tags:
Home Assistant: `2023.8.4`
ZWave JS UI: `8.23`

I initially saw this on tag `8.25`, and I reverted back to `8.23` initially with the same data & config, but the problem persisted. I then reinstalled `8.23` completely (deleting all configs & data) thinking there was some sort of new error in `8.25`, but this seems to have been unfounded.

I am using a Nortek HUSBZB-1 Zwave/Zigbee combo controller. However, I am only using the ZWave functionality at this time.

**Comment by robertsLando** [comment]
Tried 8.26?

**Comment by AlCalzone** [comment]
> Could it be that for some reasons args is undefined in `ZWaveNotificationCallback` ?

I checked all locations where that event gets emitted. The `args` object is always immediately part of the call, so no.

**Comment by robertsLando** [comment]
I submitted a fix to include error stack in error message. I will create a quick patch so you can try that and report me the new error when happens so we can understand the root cause

**Comment by robertsLando** [comment]
@evan-swinney You can use `master` tag when this ends: 

https://github.com/zwave-js/zwave-js-ui/actions/runs/6310143058/job/17131491025

**Comment by robertsLando** [comment]
Use v 9+ version and let us know when possible

**Comment by evan-swinney** [comment]
Will do as soon as I can!

**Comment by evan-swinney** [comment]
@robertsLando I upgraded the ZWave-UI container to the `9.0.1` tag. I did not delete or modify any configuration data when I did this.

Now no devices show up in the device list, and the health endpoint is returning `500` and the container is now in a slow infinite restart loop.

If you think I should delete all configuration data, I can.

**Comment by robertsLando** [comment]
@evan-swinney 
Please make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` and attach it here as a file (drag & drop into the text field).

Then you could revert to previous version, we need to sort out what's going on with your instance

**Comment by AlCalzone** [comment]
@evan-swinney you might be affected by this:
https://github.com/zwave-js/node-zwave-js/issues/6341

**Comment by evan-swinney** [comment]
In the process of getting you the logs, I had my log level set on Silly and logging to a file the whole time. However, I changed this to the Debug level, and as soon as I saved the configuration, it started working again, sending data to Home Assistant and all of my devices appear in the list now.

I have some of the Silly level logs, if that'd be helpful. I can also wait until the problem occurs again with the log level at Debug.

**Comment by AlCalzone** [comment]
I need to do some filtering, but those logs may still be helpful.

**Comment by evan-swinney** [comment]
I was able to just leave it over night and it started happening again, so I have logs in Debug mode now. This time the devices remain in the list, but the values are still not updating and the unhandled exception is in the ZWave UI log again. I believe this is as close to the original problem as we'll get.

Attached are both the ZWave UI and ZWave JS logs.
[z-ui_2023-10-01.log](https://github.com/zwave-js/zwave-js-ui/files/12778330/z-ui_2023-10-01.log)
[zwavejs_2023-10-01.log](https://github.com/zwave-js/zwave-js-ui/files/12778331/zwavejs_2023-10-01.log)

**Comment by robertsLando** [comment]
@AlCalzone 

```
2023-10-01 03:45:27.428 ERROR APP: Unhandled Rejection, reason: TypeError: Cannot read properties of undefined (reading 'label')
TypeError: Cannot read properties of undefined (reading 'label')
    at MultilevelSensorCCReport.persistValues (/usr/src/app/node_modules/@zwave-js/cc/src/cc/MultilevelSensorCC.ts:673:20)
    at Driver.persistCCValues (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:4435:6)
    at Driver.serialport_onData (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:3072:11)
```
