### ISSUE TITLE
Asking for a "rebuild routes" on a particular node triggers error message

### ISSUE THREAD

**Issue by jfhautenauven** [zwave-js/zwave-js-ui#3316]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Snap

### Z-Wave JS UI version

9.0.3

### ZwaveJS version

12.0.2

### Describe the bug

When trying to ask for a rebuild route on a particular node (I mean by going via the node advanced options), there is an error stating something about SUC ... that ... literally SUCks :D 

![image](https://github.com/zwave-js/zwave-js-ui/assets/83645528/b8fa59ef-8bd0-4a94-8bf7-fd32eaf81745)

I guess it's something related to the recent revamp of the backend API.

### To Reproduce

Go into the dashboard of devices
Select one victim amongst the available nodes
Expand the tab of that node
On the right upper part of that node tab, click on Advanced
Then Advanced Options
Then "Rebuild routes"

### Expected behavior

Routes are getting rebuilt without error message.

### Additional context

As a side node, rebuilding ALL the routes, so via the option on the right lower corner of screen (blue circle with lines) , so I mean rebuilding all the routes in the network seems to work.
BUT 

The animation of the turning circle in the status column doesn't show as it used to.
No turning blue circle to indicate which nodes are still rebuilding their routes.

![image](https://github.com/zwave-js/zwave-js-ui/assets/83645528/a1a90d42-dd9c-4dbb-b3e4-789484504078)

**Comment by robertsLando** [comment]
@jfhautenauven By digging into this I think this is a driver error so something for @AlCalzone 

```
ZWaveError: To assign a return route to the SUC (node ID 1), assignSUCReturnRoutes() must be used! (ZW0322)
    at ZWaveController.assignReturnRoutes (zwave-js/src/lib/controller/Controller.ts:4568:10)
    at ZWaveController.rebuildNodeRoutesInternal (zwave-js/src/lib/controller/Controller.ts:4233:18)
    at ZWaveController.rebuildNodeRoutes (zwave-js/src/lib/controller/Controller.ts:4106:11)
    at ZwaveClient.rebuildNodeRoutes (zwave-js-ui/lib/ZwaveClient.ts:2112:22)
    at ZwaveClient.callApi (zwave-js-ui/lib/ZwaveClient.ts:2693:20)
    at Socket.<anonymous> (zwave-js-ui/app.ts:503:26)
```

**Comment by robertsLando** [comment]
@jfhautenauven About the `status` not updating. There is a dedicated column that shows the rebuild routes status that I just noticed it's still named `Heal`. I think you edited the columns and that is hidden because it should be on the right side of status. I just pushed a change to name it `Rebuild Routes` instead but in order to have it back simply click on `reset table` or click on columns and be sure the `Heal` column is checked
