### ISSUE TITLE
Startup Bug in Container

### ISSUE THREAD

**Issue by BenjaminQuandt** [zwave-js/zwave-js-ui#3328]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

idk

### ZwaveJS version

9.1.0.69d9d4c

### Describe the bug

Hi i used ur container:
zwavejs/zwavejs2mqtt:latest

basically like that:
```
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=fvlmGffKl7zHPr52BeCTzfhulVuuYZRY
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      # Uncomment if you want logs time and dates to match your timezone instead of UTC
      # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=Europe/​Berlin
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      - '/dev/serial/by-id/<usb-Silicon_Labs_...>:/dev/zwave'
    volumes:
      - /opt/z-wave-js/:/usr/src/app/store
    ports:
      - "8091:8091" # port for web interface
      - "3000:3000" # port for Z-Wave JS websocket server
```

i started, stopped and started again and clicked a bit around ans tryed to use it. I ended up getting Type errors:
```
zwavejs2mqtt  | 2023-10-07 17:29:44.346 WARN STORE: settings.json not found
zwavejs2mqtt  | 2023-10-07 17:29:44.353 WARN STORE: scenes.json not found
zwavejs2mqtt  | 2023-10-07 17:29:44.363 INFO APP: Listening on port 8091 host 0.0.0.0 protocol HTTP
zwavejs2mqtt  | 2023-10-07 17:29:44.381 WARN BACKUP: Store backup is disabled
zwavejs2mqtt  | 2023-10-07 17:29:44.382 WARN BACKUP: Nvm backup is disabled
zwavejs2mqtt  | 2023-10-07 17:29:44.384 WARN Z-WAVE: Z-Wave driver not inited, no port configured
zwavejs2mqtt  | 2023-10-07 17:29:55.155 INFO APP: GET / 200 6.224 ms - 1680
zwavejs2mqtt  | 2023-10-07 17:29:55.206 INFO APP: GET /registerSW.js 200 5.717 ms - 136
zwavejs2mqtt  | 2023-10-07 17:29:55.212 INFO APP: GET /assets/index-f4e18cbd.css 200 8.758 ms - 649408
zwavejs2mqtt  | 2023-10-07 17:29:55.220 INFO APP: GET /assets/index-186e3042.js 200 11.071 ms - 1146317
zwavejs2mqtt  | 2023-10-07 17:29:55.372 INFO APP: GET /assets/Login-a80f12dd.js 200 5.603 ms - 4157
zwavejs2mqtt  | 2023-10-07 17:29:55.375 INFO APP: GET /assets/Login-f3260011.css 200 7.775 ms - 5433
zwavejs2mqtt  | 2023-10-07 17:29:55.417 INFO APP: GET /api/auth-enabled 200 17.215 ms - 29
zwavejs2mqtt  | 2023-10-07 17:29:55.434 INFO APP: GET /favicon.ico 200 4.649 ms - 923
zwavejs2mqtt  | 2023-10-07 17:29:55.435 INFO APP: GET /assets/ControlPanel-83ccf7f1.js 200 3.947 ms - 18049
zwavejs2mqtt  | 2023-10-07 17:29:55.450 INFO APP: GET /logo.svg 200 2.027 ms - 1895
zwavejs2mqtt  | 2023-10-07 17:29:55.475 INFO APP: GET /favicon.ico 304 3.731 ms - -
zwavejs2mqtt  | 2023-10-07 17:29:55.485 INFO APP: GET /assets/MaterialIcons-Regular-5743ed3d.woff2 200 14.207 ms - 125116
zwavejs2mqtt  | 2023-10-07 17:29:55.497 INFO APP: GET /assets/index-d828140d.js 200 3.770 ms - 19736
zwavejs2mqtt  | 2023-10-07 17:29:55.500 INFO APP: GET /assets/mdi-4fe99e39.js 200 6.661 ms - 9426
zwavejs2mqtt  | 2023-10-07 17:29:55.501 INFO APP: GET /assets/vuedraggable.umd-561bbcd1.js 200 4.936 ms - 71040
zwavejs2mqtt  | 2023-10-07 17:29:55.502 INFO APP: GET /assets/index-d98f5afd.css 200 6.706 ms - 393
zwavejs2mqtt  | 2023-10-07 17:29:55.503 INFO APP: GET /assets/DialogAdvanced-eaabda04.css 200 7.332 ms - 450
zwavejs2mqtt  | 2023-10-07 17:29:55.504 INFO APP: GET /assets/DialogAdvanced-add35863.js 200 7.775 ms - 1306
zwavejs2mqtt  | 2023-10-07 17:29:55.512 INFO APP: GET /favicon.ico 304 3.442 ms - -
zwavejs2mqtt  | 2023-10-07 17:29:55.529 INFO APP: GET /favicon.ico 304 0.691 ms - -
zwavejs2mqtt  | 2023-10-07 17:29:55.556 INFO APP: GET /assets/ColumnFilter-4b95717f.js 200 4.892 ms - 3498
zwavejs2mqtt  | 2023-10-07 17:29:55.608 INFO APP: GET /assets/ColumnFilterNumber-e937dd41.js 200 1.819 ms - 1774
zwavejs2mqtt  | 2023-10-07 17:29:55.609 INFO APP: GET /assets/ColumnFilterString-75652514.js 200 2.218 ms - 1257
zwavejs2mqtt  | 2023-10-07 17:29:55.611 INFO APP: GET /assets/ColumnFilterBoolean-21467daa.js 200 0.762 ms - 703
zwavejs2mqtt  | 2023-10-07 17:29:55.617 INFO APP: GET /assets/ColumnFilterDate-43cecbcb.js 200 0.655 ms - 1196
zwavejs2mqtt  | 2023-10-07 17:29:56.582 INFO APP: GET /api/settings 200 1072.455 ms - 12844
zwavejs2mqtt  | 2023-10-07 17:29:56.597 INFO APP: GET /api/auth-enabled 304 4.476 ms - -
zwavejs2mqtt  | 2023-10-07 17:30:04.790 WARN Z-WAVE: Zwavejs driver is not ready yet, statistics will be disabled on driver initialization
zwavejs2mqtt  | 2023-10-07 17:30:04.791 INFO APP: POST /api/statistics 200 16.899 ms - 90
zwavejs2mqtt  | 2023-10-07 17:30:05.054 INFO APP: GET /assets/index-308e2a9c.js 200 2.599 ms - 108901
zwavejs2mqtt  | 2023-10-07 17:30:15.233 ERROR APP: Cannot set properties of undefined (setting 'versions')
zwavejs2mqtt  | TypeError: Cannot set properties of undefined (setting 'versions')
zwavejs2mqtt  |     at /usr/src/app/server/app.js:925:35
zwavejs2mqtt  |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
zwavejs2mqtt  |     at next (/usr/src/app/node_modules/express/lib/router/route.js:144:13)
zwavejs2mqtt  |     at isAuthenticated (/usr/src/app/server/app.js:637:16)
zwavejs2mqtt  |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
zwavejs2mqtt  |     at next (/usr/src/app/node_modules/express/lib/router/route.js:144:13)
zwavejs2mqtt  |     at /usr/src/app/node_modules/express-rate-limit/dist/index.cjs:659:7
zwavejs2mqtt  |     at /usr/src/app/node_modules/express-rate-limit/dist/index.cjs:576:5
zwavejs2mqtt  | 2023-10-07 17:30:15.234 INFO APP: POST /api/versions 200 7.002 ms - 85
zwavejs2mqtt  | 2023-10-07 17:30:17.480 INFO APP: GET /assets/SmartStart-263ba1c4.js 200 2.328 ms - 8430
zwavejs2mqtt  | 2023-10-07 17:30:17.507 INFO Z-WAVE: Calling api getProvisioningEntries with args: [ [length]: 0 ]
zwavejs2mqtt  | 2023-10-07 17:30:17.515 ERROR APP: Unhandled Rejection, reason: TypeError: Cannot read properties of undefined (reading 'isInBootloader')
zwavejs2mqtt  | TypeError: Cannot read properties of undefined (reading 'isInBootloader')
zwavejs2mqtt  |     at ZwaveClient.callApi (/usr/src/app/server/lib/ZwaveClient.js:2601:45)
zwavejs2mqtt  |     at Socket.<anonymous> (/usr/src/app/server/app.js:507:47)
zwavejs2mqtt  |     at Socket.emit (node:events:525:35)
zwavejs2mqtt  |     at Socket.emitUntyped (/usr/src/app/node_modules/socket.io/dist/typed-events.js:69:22)
zwavejs2mqtt  |     at /usr/src/app/node_modules/socket.io/dist/socket.js:704:39
zwavejs2mqtt  |     at processTicksAndRejections (node:internal/process/task_queues:77:11)
zwavejs2mqtt  | 2023-10-07 17:30:20.573 INFO APP: GET /assets/Mesh-890e614e.js 200 4.085 ms - 2866
zwavejs2mqtt  | 2023-10-07 17:30:20.575 INFO APP: GET /assets/Mesh-1b8d31eb.css 200 4.580 ms - 264
zwavejs2mqtt  | 2023-10-07 17:30:20.597 INFO APP: GET /assets/NodePanel-69dab776.css 200 4.984 ms - 88
zwavejs2mqtt  | 2023-10-07 17:30:20.599 INFO APP: GET /assets/NodePanel-9afe635b.js 200 5.752 ms - 14964
zwavejs2mqtt  | 2023-10-07 17:30:20.601 INFO APP: GET /assets/ZwaveGraph-fe07d4ee.css 200 7.541 ms - 220266
zwavejs2mqtt  | 2023-10-07 17:30:20.602 INFO APP: GET /assets/ZwaveGraph-8de3b6c2.js 200 4.896 ms - 573250
zwavejs2mqtt  | 2023-10-07 17:30:20.605 INFO APP: GET /assets/DialogHealthCheck-2228ed6c.css 200 1.397 ms - 44
zwavejs2mqtt  | 2023-10-07 17:30:20.606 INFO APP: GET /assets/DialogHealthCheck-54fe9144.js 200 2.633 ms - 12272
zwavejs2mqtt  | 2023-10-07 17:30:21.086 INFO Z-WAVE: Calling api refreshNeighbors with args: [ [length]: 0 ]
zwavejs2mqtt  | 2023-10-07 17:30:21.089 ERROR APP: Unhandled Rejection, reason: TypeError: Cannot read properties of undefined (reading 'isInBootloader')
zwavejs2mqtt  | TypeError: Cannot read properties of undefined (reading 'isInBootloader')
zwavejs2mqtt  |     at ZwaveClient.callApi (/usr/src/app/server/lib/ZwaveClient.js:2601:45)
zwavejs2mqtt  |     at Socket.<anonymous> (/usr/src/app/server/app.js:507:47)
zwavejs2mqtt  |     at Socket.emit (node:events:525:35)
zwavejs2mqtt  |     at Socket.emitUntyped (/usr/src/app/node_modules/socket.io/dist/typed-events.js:69:22)
zwavejs2mqtt  |     at /usr/src/app/node_modules/socket.io/dist/socket.js:704:39
zwavejs2mqtt  |     at processTicksAndRejections (node:internal/process/task_queues:77:11)
zwavejs2mqtt  | 2023-10-07 17:30:21.340 INFO APP: GET /assets/Store-198510be.js 200 3.503 ms - 10911
zwavejs2mqtt  | 2023-10-07 17:30:21.342 INFO APP: GET /assets/Store-79348188.css 200 5.320 ms - 787
zwavejs2mqtt  | 2023-10-07 17:30:21.369 INFO APP: GET /api/store 200 9.463 ms - 633
zwavejs2mqtt  | 2023-10-07 17:30:25.350 INFO APP: GET /assets/Debug-aad11cfb.js 200 2.865 ms - 16343
zwavejs2mqtt  | 2023-10-07 17:30:35.635 INFO APP: GET /assets/Scenes-ea10ecb1.js 200 2.165 ms - 5750
zwavejs2mqtt  | 2023-10-07 17:30:35.652 INFO Z-WAVE: Calling api _getScenes with args: [ [length]: 0 ]
zwavejs2mqtt  | 2023-10-07 17:30:35.654 ERROR APP: Unhandled Rejection, reason: TypeError: Cannot read properties of undefined (reading 'isInBootloader')
zwavejs2mqtt  | TypeError: Cannot read properties of undefined (reading 'isInBootloader')
zwavejs2mqtt  |     at ZwaveClient.callApi (/usr/src/app/server/lib/ZwaveClient.js:2601:45)
zwavejs2mqtt  |     at Socket.<anonymous> (/usr/src/app/server/app.js:507:47)
zwavejs2mqtt  |     at Socket.emit (node:events:525:35)
zwavejs2mqtt  |     at Socket.emitUntyped (/usr/src/app/node_modules/socket.io/dist/typed-events.js:69:22)
zwavejs2mqtt  |     at /usr/src/app/node_modules/socket.io/dist/socket.js:704:39
zwavejs2mqtt  |     at processTicksAndRejections (node:internal/process/task_queues:77:11)
zwavejs2mqtt  | 2023-10-07 17:30:35.660 INFO APP: GET /assets/DialogSceneValue-54c6d30a.js 200 9.233 ms - 3089
zwavejs2mqtt  | 2023-10-07 17:30:37.106 INFO APP: GET /assets/Settings-4d210e5c.js 200 5.293 ms - 70863
zwavejs2mqtt  | 2023-10-07 17:30:37.107 INFO APP: GET /assets/Settings-a9cc4df2.css 200 3.159 ms - 78
zwavejs2mqtt  | 2023-10-07 17:30:37.108 INFO APP: GET /assets/items-de2ab019.js 200 3.149 ms - 142
zwavejs2mqtt  | 2023-10-07 17:30:37.130 INFO APP: GET /assets/DialogGatewayValue-a5468160.js 200 3.381 ms - 8290
zwavejs2mqtt  | 2023-10-07 17:30:37.132 INFO APP: GET /assets/DialogGatewayValue-921e0920.css 200 5.037 ms - 61
zwavejs2mqtt  | 2023-10-07 17:30:38.226 INFO APP: GET /api/settings 200 1073.853 ms - 12891
zwavejs2mqtt  | 2023-10-07 17:30:38.244 INFO APP: GET /api/auth-enabled 304 2.297 ms - -
zwavejs2mqtt  | 2023-10-07 17:30:52.468 INFO Z-WAVE: Calling api getProvisioningEntries with args: [ [length]: 0 ]
zwavejs2mqtt  | 2023-10-07 17:30:52.470 ERROR APP: Unhandled Rejection, reason: TypeError: Cannot read properties of undefined (reading 'isInBootloader')
zwavejs2mqtt  | TypeError: Cannot read properties of undefined (reading 'isInBootloader')
zwavejs2mqtt  |     at ZwaveClient.callApi (/usr/src/app/server/lib/ZwaveClient.js:2601:45)
zwavejs2mqtt  |     at Socket.<anonymous> (/usr/src/app/server/app.js:507:47)
zwavejs2mqtt  |     at Socket.emit (node:events:525:35)
zwavejs2mqtt  |     at Socket.emitUntyped (/usr/src/app/node_modules/socket.io/dist/typed-events.js:69:22)
zwavejs2mqtt  |     at /usr/src/app/node_modules/socket.io/dist/socket.js:704:39
zwavejs2mqtt  |     at processTicksAndRejections (node:internal/process/task_queues:77:11)
zwavejs2mqtt  | 2023-10-07 17:31:02.221 INFO APP: GET /assets/SmartView-739dc304.js 200 2.161 ms - 8871
zwavejs2mqtt  | 2023-10-07 17:31:02.232 INFO APP: GET /assets/ExpandedNode-55e320d0.js 200 2.830 ms - 14020
zwavejs2mqtt  | 2023-10-07 17:31:02.233 INFO APP: GET /assets/ExpandedNode-9f727a42.css 200 1.263 ms - 387
zwavejs2mqtt  | 2023-10-07 17:31:05.141 INFO Z-WAVE: Calling api getProvisioningEntries with args: [ [length]: 0 ]
zwavejs2mqtt  | 2023-10-07 17:31:05.143 ERROR APP: Unhandled Rejection, reason: TypeError: Cannot read properties of undefined (reading 'isInBootloader')
zwavejs2mqtt  | TypeError: Cannot read properties of undefined (reading 'isInBootloader')
zwavejs2mqtt  |     at ZwaveClient.callApi (/usr/src/app/server/lib/ZwaveClient.js:2601:45)
zwavejs2mqtt  |     at Socket.<anonymous> (/usr/src/app/server/app.js:507:47)
zwavejs2mqtt  |     at Socket.emit (node:events:525:35)
zwavejs2mqtt  |     at Socket.emitUntyped (/usr/src/app/node_modules/socket.io/dist/typed-events.js:69:22)
zwavejs2mqtt  |     at /usr/src/app/node_modules/socket.io/dist/socket.js:704:39
zwavejs2mqtt  |     at processTicksAndRejections (node:internal/process/task_queues:77:11)
```

### To Reproduce

start docker and maybe click around in ui or try to connect. did nothing special...

might be a problem with the z-wave stick but 'type errors' seems to be a problem anyways

### Expected behavior

no Type errors -> propper exception handeling with speeking errors.

**Comment by BenjaminQuandt** [comment]
i swaped to zwavejs/zwave-js-ui:latest
might be the same. same startup error.

i got into the ui. set up debug log and ws for hs.
restartet.
and the type errors are gone.
