### ISSUE TITLE
Build using custom node-zwave-js fails

### ISSUE THREAD

**Issue by poelstra** [zwave-js/zwave-js-ui#3352]
I'm trying to debug an issue in node-zwave-js, and want to use zwave-js-ui as the 'host'.
I first cloned `node-zwave-js`, following the development instructions to `yarn` and `yarn build`.
Then I cloned `zwave-js-ui`, following the development instructions to `yarn` and `yarn build`.
So far so good.

Then, I followed the instructions at https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github to link the master version into `zwave-js-ui`:
```sh
martin@yoga ~/external_src/zwave-js-ui (master) $ yarn link ../node-zwave-js/ --all
➤ YN0000: ┌ Resolution step
➤ YN0002: │ zwave-js-ui@workspace:. doesn't provide @babel/core (pd92f5), requested by @babel/register
➤ YN0002: │ zwave-js-ui@workspace:. doesn't provide @egjs/hammerjs (pb72e2), requested by vis-network
➤ YN0002: │ zwave-js-ui@workspace:. doesn't provide component-emitter (p9f27e), requested by vis-network
➤ YN0002: │ zwave-js-ui@workspace:. doesn't provide esbuild (pe0be1), requested by esbuild-register
➤ YN0002: │ zwave-js-ui@workspace:. doesn't provide keycharm (p9e48c), requested by vis-network
➤ YN0002: │ zwave-js-ui@workspace:. doesn't provide timsort (pd6433), requested by vis-network
➤ YN0002: │ zwave-js-ui@workspace:. doesn't provide uuid (p8cb88), requested by vis-data
➤ YN0002: │ zwave-js-ui@workspace:. doesn't provide uuid (p57e35), requested by vis-network
➤ YN0002: │ zwave-js-ui@workspace:. doesn't provide vis-util (p81018), requested by vis-data
➤ YN0002: │ zwave-js-ui@workspace:. doesn't provide vis-util (p6ebf7), requested by vis-network
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 228ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 347ms
➤ YN0000: ┌ Link step
➤ YN0072: │ The application uses portals and that's why --preserve-symlinks Node option is required for launching it
➤ YN0000: └ Completed in 0s 953ms
➤ YN0000: Done with warnings in 1s 765ms
```

However, building gives me:
```sh
martin@yoga ~/external_src/zwave-js-ui (master *) $ yarn build
vite v4.4.9 building for production...
✓ 379 modules transformed.
[vite-plugin-pwa:build] "isValidDSK" is not exported by "../node-zwave-js/packages/core/build/index_safe.js", imported by "src/lib/utils.js".
file: /home/martin/external_src/zwave-js-ui/src/lib/utils.js:1:9
1: import { isValidDSK } from '@zwave-js/core/safe'
            ^
2: 
3: export function copy(o) {
error during build:
RollupError: "isValidDSK" is not exported by "../node-zwave-js/packages/core/build/index_safe.js", imported by "src/lib/utils.js".
    at error (file:///home/martin/external_src/zwave-js-ui/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at Module.error (file:///home/martin/external_src/zwave-js-ui/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:13745:16)
    at Module.traceVariable (file:///home/martin/external_src/zwave-js-ui/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:14175:29)
    at ModuleScope.findVariable (file:///home/martin/external_src/zwave-js-ui/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:12615:39)
    at FunctionScope.findVariable (file:///home/martin/external_src/zwave-js-ui/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at ChildScope.findVariable (file:///home/martin/external_src/zwave-js-ui/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:7124:38)
    at Identifier.bind (file:///home/martin/external_src/zwave-js-ui/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:8319:40)
    at CallExpression.bind (file:///home/martin/external_src/zwave-js-ui/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
    at CallExpression.bind (file:///home/martin/external_src/zwave-js-ui/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:9890:15)
    at LogicalExpression.bind (file:///home/martin/external_src/zwave-js-ui/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
ERROR: "build:ui" exited with 1.
```

I also tried to just run `yarn dev` and `yarn dev:server` hoping this would perhaps use a different resolver, but that just throws a similar error about `isValidDSK` in the browser's console.

Looking in `../node-zwave-js/packages/core/build/index_safe.js`, the mentioned function does seem to be exported (from `/security/shared_safe`), and there don't seem to be any recent Git changes related to this on both sides.

What am I doing wrong?

Node: v18.16.0
Yarn: 3.2.1

**Comment by robertsLando** [comment]
The commands you used seems good to me, are you sure you have also run the `yarn build` command inside node-zwave-js repo and that it completed correctly?

**Comment by AlCalzone** [comment]
I remember a very similar error when trying to link zwave-js locally. I think this might be related to the vite cache or preserving symlinks.

**Comment by AlCalzone** [comment]
Unfortunately those instructions aren't up to date anymore, due to the switch to `vite` in this repo. There are a few additional changes that need to be made:
1. `vite.config.js` -> `defineConfig` -> `resolve`: add `preserveSymlinks: true`
2. `package.json`: If `yarn` complains about non-matching dependencies, add a compatible version of them to `resolutions` (this property is already added by `yarn link`). In my case I had to add
    ```
    "fs-extra": "npm:11.1.1",
    "semver": "npm:7.3.8"
    ```
3. For debugging and watching, edit `nodemon.json`:
	```diff
	-	"watch": ["**/*.ts", "package.json", "tsconfig.json"],
	+	"watch": ["**/*.ts", "package.json", "tsconfig.json", "../node-zwave-js/packages/*/build/**/*.js"],
	-	"ext": "ts,json",
	+	"ext": "ts,json,js",
		"ignore": ["pkg", "store", "node_modules", "src", "dist", "server"],
	-	"exec": "node --inspect=7004 --trace-warnings -r esbuild-register bin/www.ts"
	+	"exec": "node --inspect=7004 --trace-warnings -r ./esbuild-register bin/www.ts"
	```
	and add a file `esbuild-register.js` in the root with this content:
	```js
	'use strict'
	
	const { register } = require('esbuild-register/dist/node')
	
	register({
		hookMatcher(f) {
			return f.endsWith('.ts')
		},
		// Prevent esbuild from adding a "2" to the names of CC classes for some reason.
		keepNames: true,
		// Target the correct node version in transpilation
		target: `node${process.versions.node}`,
		// Stick to legacy decorators for now
		tsconfigRaw: {
			compilerOptions: {
				experimentalDecorators: true,
			},
		},
	})
	```

@robertsLando maybe we should do 1. and 3. by default to make this easier?

**Comment by robertsLando** [comment]
Ok for me!

**Comment by robertsLando** [comment]
@poelstra try https://github.com/zwave-js/zwave-js-ui/pull/3354

**Comment by poelstra** [comment]
Thnx for the blazing fast response ;)
I'll try it out tomorrow.

18 okt. 2023 09:50:42 Daniel Lando ***@***.***>:

**Comment by robertsLando** [comment]
I will merge it once I get your feedback :)

**Comment by poelstra** [comment]
@robertsLando Works like a charm!

I'm not sure whether/when step 2 mentioned by @AlCalzone is needed, yarn didn't complain for me. So everything works again now, using the current instructions.
