### ISSUE TITLE
Zwave-js-ui failed control panel

### ISSUE THREAD

**Issue by ViaudJV** [zwave-js/zwave-js-ui#3399]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [ ] I have read the changelog and my problem is not mentioned there.

### Deploy method

Snap

### Z-Wave JS UI version

9.0.3

### ZwaveJS version

9.0.3

### Describe the bug

I had a hard reebot on my machine.
Now Zwave works well, i can piote my windows but with my brower when i go to my control panel i have this message

`TypeError: Cannot read properties of undefined (reading 'replace')
    at /snap/zwave-js-ui/259/lib/zwave-js-ui/server/app.js:448:51
    at Layer.handle [as handle_request] (/snap/zwave-js-ui/259/lib/zwave-js-ui/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/snap/zwave-js-ui/259/lib/zwave-js-ui/node_modules/express/lib/router/index.js:328:13)
    at /snap/zwave-js-ui/259/lib/zwave-js-ui/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/snap/zwave-js-ui/259/lib/zwave-js-ui/node_modules/express/lib/router/index.js:346:12)
    at next (/snap/zwave-js-ui/259/lib/zwave-js-ui/node_modules/express/lib/router/index.js:280:10)
    at /snap/zwave-js-ui/259/lib/zwave-js-ui/node_modules/connect-history-api-fallback/lib/index.js:85:5
    at Layer.handle [as handle_request] (/snap/zwave-js-ui/259/lib/zwave-js-ui/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/snap/zwave-js-ui/259/lib/zwave-js-ui/node_modules/express/lib/router/index.js:328:13)
    at /snap/zwave-js-ui/259/lib/zwave-js-ui/node_modules/express/lib/router/index.js:286:9`

### To Reproduce

 I didnt a way to reproduce it

### Expected behavior

I expect to see control panel

**Comment by robertsLando** [comment]
Try with latest 9.2.3 version
