### ISSUE TITLE
Potential 9.5.0 driver issue

### ISSUE THREAD

**Issue by KmanOz** [zwave-js/zwave-js-ui#3461]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.5.0.db15612

### ZwaveJS version

12.4.0

### Describe the bug

Everything loads OK in docker and UI is accessible but no longer sees the Zoos ZST10 dongle as a controller and logs from docker show this :-

2023-12-01 20:13:25.736 ERROR APP: Unhandled Rejection, reason: TypeError: Cannot read properties of undefined (reading 'isInBootloader')
TypeError: Cannot read properties of undefined (reading 'isInBootloader')
    at ZwaveClient.callApi (/usr/src/app/server/lib/ZwaveClient.js:2632:45)
    at Socket.<anonymous> (/usr/src/app/server/app.js:507:47)
    at Socket.emit (node:events:529:35)
    at Socket.emitUntyped (/usr/src/app/node_modules/socket.io/dist/typed-events.js:69:22)
    at /usr/src/app/node_modules/socket.io/dist/socket.js:704:39
    at processTicksAndRejections (node:internal/process/task_queues:77:11)

### To Reproduce

Happens every time

### Expected behavior

I expected when I upgraded to 9.5.0 for it to continue working

**Comment by KmanOz** [comment]
> > 2023-12-01 23:02:37.423 WARN Z-WAVE: Z-Wave driver not inited, no port configured
> 
> You haven't configured any USB device.

This is in my docker compose file. Are you saying there is additional driver configuration? I have never done that before.

    devices:
      - '/dev/serial/by-path/pci-0000:00:14.0-usb-0:13:1.0-port0'
 
This is from Portainer.

<img width="933" alt="Screenshot 2023-12-02 at 5 41 08 pm" src="https://github.com/zwave-js/zwave-js-ui/assets/1904926/01795ae3-b0df-4aa6-8282-d360909fbd7c">

**Comment by KmanOz** [comment]
Wow you just jogged my memory but something weird happened. It's been a long time since I set it up. Yes I moved it to by-id. That was an old screenshot.

In the UI the port was already mapped to /dev/zwave. This has never worked. I then moved it to another serial port which also didn't work but as soon as I moved it back to /dev/zwave, it pick up my Zooz stick as a controller. It's the exact setting that were there but now works. Thank you and sorry for wasting your time.
