### ISSUE TITLE
Failed to initialize the driver when using TCP (ser2net)

### ISSUE THREAD

**Issue by theautomation** [zwave-js/zwave-js-ui#3542]
Hi, I am spending days now to connect my Zwave Aeotec Gen5 stick over TCP using ser2net to the ZwaveJS instance. When I connect the USB device directly to the zwavejs container everything works as expected, but when I want to connect the Zwave stick via TCP using ser2net, then I am getting the following errors:

From the UI:
```log
Driver: Failed to initialize the driver: ZWaveError: Timeout while waiting for a response from the controller (ZW0200) at Driver.sendMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:5256:23) at ZWaveController.identify (/usr/src/app/node_modules/zwave-js/src/lib/controller/Controller.ts:897:37) at Driver.initializeControllerAndNodes (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:1432:26) at Immediate.<anonymous> (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:1226:16) (ZW0100)
```

The log files show me that there is some invalid data, but why?
```log
2024-01-21T19:12:04.614Z DRIVER   ███████╗        ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗          ██╗ ███████╗
                                  ╚══███╔╝        ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝          ██║ ██╔════╝
                                    ███╔╝  █████╗ ██║ █╗ ██║ ███████║ ██║   ██║ █████╗            ██║ ███████╗
                                   ███╔╝   ╚════╝ ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝       ██   ██║ ╚════██║
                                  ███████╗        ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗     ╚█████╔╝ ███████║
                                  ╚══════╝         ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝      ╚════╝  ╚══════╝
2024-01-21T19:12:04.615Z DRIVER   version 12.4.1
2024-01-21T19:12:04.615Z DRIVER   
2024-01-21T19:12:04.616Z DRIVER   starting driver...
2024-01-21T19:12:04.617Z DRIVER   opening serial port tcp://10.0.99.7:3001
2024-01-21T19:12:04.628Z DRIVER   serial port opened
2024-01-21T19:12:04.630Z SERIAL » 0x15                                                                 (1 bytes)
2024-01-21T19:12:04.633Z SERIAL « [DISCARDED] invalid data 0xfffb03fffd03fffb                          (8 bytes)
2024-01-21T19:12:05.633Z DRIVER   loading configuration...
2024-01-21T19:12:05.640Z CONFIG   Using external configuration dir /usr/src/app/store/.config-db
2024-01-21T19:12:05.641Z CONFIG   version 12.4.1
2024-01-21T19:12:07.650Z DRIVER   beginning interview...
2024-01-21T19:12:07.652Z DRIVER   added request handler for AddNodeToNetwork (0x4a)...
                                  1 registered
2024-01-21T19:12:07.653Z DRIVER   added request handler for RemoveNodeFromNetwork (0x4b)...
                                  1 registered
2024-01-21T19:12:07.654Z DRIVER   added request handler for ReplaceFailedNode (0x63)...
                                  1 registered
2024-01-21T19:12:07.654Z DRIVER   added request handler for SerialAPIStarted (0x0a)...
                                  1 registered
2024-01-21T19:12:07.655Z CNTRLR   querying Serial API capabilities...
2024-01-21T19:12:07.672Z SERIAL » 0x01030007fb                                                         (5 bytes)
2024-01-21T19:12:07.674Z DRIVER » [REQ] [GetSerialApiCapabilities]
2024-01-21T19:12:08.680Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2024-01-21T19:12:08.782Z DRIVER » [REQ] [GetSerialApiCapabilities]
2024-01-21T19:12:08.783Z SERIAL » 0x01030007fb                                                         (5 bytes)
2024-01-21T19:12:09.787Z CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
                                  n 1100 ms.
2024-01-21T19:12:10.682Z SERIAL « 0x01fffe01fffd00fffb00fffd2c436f6e6e656374656420746f20706f7274206d (257 bytes)
                                  792d636f6e736f6c652873657269616c6465762c2f6465762f73657269616c2f62792d69642f75
                                  73622d303635385f303230302d696630302c393630304e38312c6c6f63616c290d0a06012b0107
                                  010100860101005afe81ffff884f1f0000fb9f7da067000080008086000000e87300000e000060
                                  0000fb012b0107010100860101005afe81ffff884f1f0000fb9f7da067000080008086000000e8
                                  7300000e0000600000fb18012b0107010100860101005afe81ffff884f1f0000fb9f7da0670000
                                  80008086000000e87300000e0000600000fb012b0107010100860101005a
2024-01-21T19:12:10.685Z SERIAL « [DISCARDED] invalid data 0xfe81ffff884f1f0000fb9f7da067000080008086 (34 bytes)
                                  000000e87300000e0000600000fb
2024-01-21T19:12:10.687Z DRIVER   Dropping message because it contains invalid data
2024-01-21T19:12:10.687Z SERIAL » [NAK]                                                                   (0x15)
2024-01-21T19:12:10.890Z DRIVER » [REQ] [GetSerialApiCapabilities]
2024-01-21T19:12:10.891Z SERIAL » 0x01030007fb                                                         (5 bytes)
2024-01-21T19:12:10.899Z SERIAL « [ACK]                                                                   (0x06)
2024-01-21T19:12:10.902Z SERIAL « 0x012b0107010100860101005afe81ffff884f1f0000fb9f7da0670000800080860 (45 bytes)
                                  00000e87300000e0000600000
2024-01-21T19:12:10.904Z SERIAL « [DISCARDED] invalid data 0xfb                                        (1 bytes)
2024-01-21T19:12:10.905Z DRIVER   Dropping message because it contains invalid data
2024-01-21T19:12:10.906Z SERIAL » [NAK]                                                                   (0x15)
2024-01-21T19:12:10.913Z SERIAL « 0x012b0107010100860101005afe81ffff884f1f0000fb9f7da0670000800080860 (45 bytes)
                                  00000e87300000e0000600000
```

ser2net and zwavejs is running as containers on top of Docker
Here my docker-compose files:

Zwavejs:
```yaml
---
version: "3.7"
services:
  zwave-js-ui:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui:latest
    restart: unless-stopped
    network_mode: host
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=mysupersecretkey
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      - TZ=Europe/Amsterdam
```

ser2net:
```yaml
---
version: "3.4"
services:
  ser2net2:
    container_name: ser2net
    image: ghcr.io/jippi/docker-ser2net
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./src/ser2net.yaml:/etc/ser2net/ser2net.yaml
    devices:
      - /dev/serial/by-id/usb-0658_0200-if00

```
ser2net.yaml:
```yaml
%YAML 1.1
---

define: &banner Connected to port \N(\d)\r\n

default:
  name: local
  value: true
  class: serialdev

default:
  name: mdns
  value: false

default:
  name: mdns-sysattrs
  value: false

connection: &my-console
  accepter: telnet(rfc2217),tcp,3001
  connector: serialdev,/dev/serial/by-id/usb-0658_0200-if00,9600N81,local
  options:
    mdns: false
    banner: *banner
```

Any idea what could be wrong?

**Comment by theautomation** [comment]
Thanks! @kpine I removed the volume on purpose so I always start a fresh clean zwavejs container when I try to solve this problem. 

I changed the ser2net config to this:
```yaml
%YAML 1.1
---

connection: &my-zwave
    accepter: tcp,3001
    enable: on
    options:
        kickolduser: true
    connector: serialdev,/dev/serial/by-id/usb-0658_0200-if00,115200N81,nobreak,local
```
Now I am getting this error in ZwaveJS UI:
```log
Driver: Serial port errored: The socket closed unexpectedly! (ZW0100)
```
And this is the log of the ser2net container:

```log
ser2net  | ser2net[7]: dev read error for device on port my-zwave: Remote end closed connection
ser2net  | ser2net[7]: dev read error for device on port my-zwave: Remote end closed connection
...
```

**Comment by theautomation** [comment]
O my ... When looking around the web I found this [issue ](https://github.com/cminyard/ser2net/issues/67) 

I added this to the ser2net config connector `keepopen(retry-time=2000,discard-badwrites),`

Compleet ser2net config
```yaml
%YAML 1.1
---

connection: &my-zwave
    accepter: tcp,3001
    enable: on
    options:
        kickolduser: true
    connector: keepopen(retry-time=2000,discard-badwrites),serialdev,/dev/serial/by-id/usb-0658_0200-if00,115200N81,nobreak,local
```
And now ZwaveJS sees the z-wave stick :tada: 

![Screenshot from 2024-01-21 21-45-35](https://github.com/zwave-js/zwave-js-ui/assets/43297525/e9c3baeb-c253-4690-a917-1bfd7b85e676)
