### ISSUE TITLE
Problem interview Heatit Z-Temp2

### ISSUE THREAD

**Issue by duylong** [zwave-js/zwave-js-ui#3578]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [ ] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.8.2.c09b638

### ZwaveJS version

12.4.3

### Describe the bug

```
2024-02-02 21:49:48.496 ERROR APP: Unhandled Rejection, reason: TypeError: Cannot read properties of undefined (reading 'get')
TypeError: Cannot read properties of undefined (reading 'get')
    at /usr/src/app/node_modules/@zwave-js/cc/src/cc/ConfigurationCC.ts:639:23
    at Array.map (<anonymous>)
    at Proxy.getBulk (/usr/src/app/node_modules/@zwave-js/cc/src/cc/ConfigurationCC.ts:638:18)
    at Proxy.get (/usr/src/app/node_modules/@zwave-js/cc/src/cc/ConfigurationCC.ts:513:19)
    at ConfigurationCC.refreshValues (/usr/src/app/node_modules/@zwave-js/cc/src/cc/ConfigurationCC.ts:1276:6)
    at ConfigurationCC.interview (/usr/src/app/node_modules/@zwave-js/cc/src/cc/ConfigurationCC.ts:1191:3)
    at interviewEndpoint (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:2166:5)
    at ZWaveNode.interviewCCs (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:2695:19)
    at ZWaveNode.interviewInternal (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:1818:9)
    at Driver.interviewNodeInternal (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:1664:10)
```

I tried several inclusion/exclusion near the controller and I still get stuck. I also increased the timeout for inclusion.

### To Reproduce

The problem appears when including during the interview or after an interview request. “NodeInfo” runs in a loop. After restarting, I always loop on "NodeInfo". 

### Expected behavior

Never had a problem during an inclusion or interview, the module is broken? It seems to work well.

### Additional context

[zwavejs_2024-02-02.log](https://github.com/zwave-js/zwave-js-ui/files/14145552/zwavejs_2024-02-02.log)
[z-ui_2024-02-02.log](https://github.com/zwave-js/zwave-js-ui/files/14145553/z-ui_2024-02-02.log)

**Comment by duylong** [comment]
I think the problem is the same https://github.com/zwave-js/node-zwave-js/issues/6563

**Comment by duylong** [comment]
I also saw that someone had the same problem https://github.com/home-assistant/frontend/issues/19440. Probably a issue with Heatit firmware 1.2.1. I contacted support, we'll see their response.
