### ISSUE TITLE
Z-Wave JS UI won't start: The "windows-1252" encoding is not supported

### ISSUE THREAD

**Issue by vilellic** [zwave-js/zwave-js-ui#3994]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.27

### ZwaveJS version

what comes with 9.27

### Describe the bug

Updated to the new version, and it didn't start anymore. Failed with error in log:
```
2024-11-12 18:10:04.339 ERROR STORE: Unhandled Rejection, reason: RangeError [ERR_ENCODING_NOT_SUPPORTED]: The "windows-1252" encoding is not supported
RangeError: The "windows-1252" encoding is not supported
    at new NodeError (node:internal/errors:405:5)
    at TextDecoder.#prepareConverter (node:internal/encoding:423:15)
    at new TextDecoder (node:internal/encoding:415:31)
    at uint8ArrayToString (/usr/src/app/node_modules/@zwave-js/shared/src/uint8array-extras.ts:312:31)
    at Bytes.toString (/usr/src/app/node_modules/@zwave-js/shared/src/Bytes.ts:136:12)
    at SerialPort.<anonymous> (/usr/src/app/node_modules/@zwave-js/serial/src/serialport/ZWaveSerialPortBase.ts:162:24)
    at SerialPort.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at SerialPort.Readable.push (node:internal/streams/readable:278:10)
```
When I took 9.26 version in to use, it started to work again.
Using first generation RaZberry Z-wave hat with Raspberry.

### To Reproduce

Update to 9.27 and start container.

### Expected behavior

That it starts.

**Comment by hansaya** [comment]
I'm having the same issue

**Comment by robertsLando** [comment]
I think that's related to latest driver release. cc @AlCalzone

**Comment by AlCalzone** [comment]
Pretty sure it is. Will take a look later.

**Comment by schford** [comment]
same for me have reverted to last verions.

****
2024-11-12 19:43:48.179 INFO STORE: Restarting client in 15 seconds, retry 13
2024-11-12 19:44:03.187 DEBUG STORE: Closing server...
2024-11-12 19:44:03.188 INFO STORE: Server closed
2024-11-12 19:44:03.188 INFO STORE: Client closed
2024-11-12 19:44:03.189 INFO STORE: Connecting to /dev/ttyUSB0
Logging to file:
        /usr/src/app/store/logs/zwavejs_2024-11-12.log
2024-11-12 19:44:03.193 INFO STORE: Zwavejs usage statistics ENABLED
2024-11-12 19:44:03.193 WARN STORE: Zwavejs driver is not ready yet, statistics will be enabled on driver initialization
2024-11-12 19:44:04.371 ERROR STORE: Unhandled Rejection, reason: RangeError [ERR_ENCODING_NOT_SUPPORTED]: The "windows-1252" encoding is not supported
RangeError: The "windows-1252" encoding is not supported
    at new NodeError (node:internal/errors:405:5)
    at TextDecoder.#prepareConverter (node:internal/encoding:423:15)
    at new TextDecoder (node:internal/encoding:415:31)
    at uint8ArrayToString (/usr/src/app/node_modules/@zwave-js/shared/src/uint8array-extras.ts:312:31)
    at Bytes.toString (/usr/src/app/node_modules/@zwave-js/shared/src/Bytes.ts:136:12)
    at SerialPort.<anonymous> (/usr/src/app/node_modules/@zwave-js/serial/src/serialport/ZWaveSerialPortBase.ts:162:24)
    at SerialPort.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at SerialPort.Readable.push (node:internal/streams/readable:278:10)
2024-11-12 19:44:08.569 INFO STORE: Restarting client in 15 seconds, retry 14

**Comment by clsferguson** [comment]
Ditto, I've also having this issue.
