### ISSUE TITLE
9.27.0 linux won't start

### ISSUE THREAD

**Issue by luckyjay** [zwave-js/zwave-js-ui#3995]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

PKG executable

### Z-Wave JS UI version

9.27.0

### ZwaveJS version

14.3.1

### Describe the bug

Attempting to launch zwave-js-ui-linux throws an error, execution stops:
![image](https://github.com/user-attachments/assets/fd70b63d-3bfd-4263-bd93-ddea6df5aa60)

### To Reproduce

Download and attempt to run 9.27.0-linux.

Environment is Ubuntu 24 LTS x64 VM on Proxmox, fully patched/updated.

### Expected behavior

Normal execution

**Comment by robertsLando** [comment]
@AlCalzone seems that latest zwave-js version broke esbuild build :(

**Comment by rhansma** [comment]
I can confirm the 9.27 build is broken on Linux. I'm receiving a different error though, not sure if it's related to the broken build @robertsLando is reporting.

```
2024-11-12 18:17:44.513 ERROR STORE: Unhandled Rejection, reason: RangeError [ERR_ENCODING_NOT_SUPPORTED]: The "windows-1252" encoding is not supported
RangeError: The "windows-1252" encoding is not supported
    at new NodeError (node:internal/errors:405:5)
    at TextDecoder.#prepareConverter (node:internal/encoding:423:15)
    at new TextDecoder (node:internal/encoding:415:31)
    at uint8ArrayToString (/usr/src/app/node_modules/@zwave-js/shared/src/uint8array-extras.ts:312:31)
    at Bytes.toString (/usr/src/app/node_modules/@zwave-js/shared/src/Bytes.ts:136:12)
    at SerialPort.<anonymous> (/usr/src/app/node_modules/@zwave-js/serial/src/serialport/ZWaveSerialPortBase.ts:162:24)
    at SerialPort.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at SerialPort.Readable.push (node:internal/streams/readable:278:10)
2024-11-12 18:17:50.512 INFO STORE: Restarting client in 15 seconds, retry 243
2024-11-12 18:18:05.526 INFO STORE: Server closed
2024-11-12 18:18:05.528 INFO STORE: Client closed
2024-11-12 18:18:05.537 INFO STORE: Connecting to /dev/zwave
```

Rolling back to version 9.26 does fix my system.

**Comment by AlCalzone** [comment]
I'll try to figure out what's going on.

**Comment by AlCalzone** [comment]
And where the heck does that text encoding come from?!

**Comment by chrisuthe** [comment]
> I can confirm the 9.27 build is broken on Linux. I'm receiving a different error though, not sure if it's related to the broken build @robertsLando is reporting.
> 
> ```
> 2024-11-12 18:17:44.513 ERROR STORE: Unhandled Rejection, reason: RangeError [ERR_ENCODING_NOT_SUPPORTED]: The "windows-1252" encoding is not supported
> RangeError: The "windows-1252" encoding is not supported
>     at new NodeError (node:internal/errors:405:5)
>     at TextDecoder.#prepareConverter (node:internal/encoding:423:15)
>     at new TextDecoder (node:internal/encoding:415:31)
>     at uint8ArrayToString (/usr/src/app/node_modules/@zwave-js/shared/src/uint8array-extras.ts:312:31)
>     at Bytes.toString (/usr/src/app/node_modules/@zwave-js/shared/src/Bytes.ts:136:12)
>     at SerialPort.<anonymous> (/usr/src/app/node_modules/@zwave-js/serial/src/serialport/ZWaveSerialPortBase.ts:162:24)
>     at SerialPort.emit (node:events:517:28)
>     at addChunk (node:internal/streams/readable:368:12)
>     at readableAddChunk (node:internal/streams/readable:341:9)
>     at SerialPort.Readable.push (node:internal/streams/readable:278:10)
> 2024-11-12 18:17:50.512 INFO STORE: Restarting client in 15 seconds, retry 243
> 2024-11-12 18:18:05.526 INFO STORE: Server closed
> 2024-11-12 18:18:05.528 INFO STORE: Client closed
> 2024-11-12 18:18:05.537 INFO STORE: Connecting to /dev/zwave
> ```
> 
> Rolling back to version 9.26 does fix my system.

Receiving same error on 9.27 as a truenas scale app. Dropping to 9.26 fixes the issue as well.

**Comment by 2Fake** [comment]
Having the same issue while using docker on debian

**Comment by AlCalzone** [comment]
> I'm able to reproduce this with:
> 
> ```
> npm run bundle
> cd build
> node index.js
> ```

No issue for me on Node 22.8.0, except that all assets are missing when opening the web UI.
Trying Docker now.

**Comment by AlCalzone** [comment]
9.27.1 should fix this

**Comment by rhansma** [comment]
> 9.27.1 should fix this

I can confirm it works with version 9.27.1. Thanks for the quick fix!

**Comment by luckyjay** [comment]
Nice work guys, issue resolved. Thanks!
