### ISSUE TITLE
9.27.0 Docker won't start on Aeotec Z-Stick Gen5+

### ISSUE THREAD

**Issue by thenoid** [zwave-js/zwave-js-ui#3997]
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

9.27.0.f3c4ac5

### ZwaveJS version

14.3.1

### Describe the bug

After upgrading to the 9.27.0 docker image, it is failing to start.  Rebooted the box, unplugged/replugged the dongle, nothing works

### To Reproduce

Upgrade from 9.26.0 -> 9.27.0

### Expected behavior

it starts up.

### Additional context
Downgrading to 9.26.0 and it starts right up.

Log output isn't super helpful, even on "Silly"
```
2024-11-12T18:49:30.260Z DRIVER   ███████╗        ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗          ██╗ ███████╗
                                  ╚══███╔╝        ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝          ██║ ██╔════╝
                                    ███╔╝  █████╗ ██║ █╗ ██║ ███████║ ██║   ██║ █████╗            ██║ ███████╗
                                   ███╔╝   ╚════╝ ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝       ██   ██║ ╚════██║
                                  ███████╗        ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗     ╚█████╔╝ ███████║
                                  ╚══════╝         ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝      ╚════╝  ╚══════╝
2024-11-12T18:49:30.260Z DRIVER   version 14.3.1
2024-11-12T18:49:30.261Z DRIVER   
2024-11-12T18:49:30.261Z DRIVER   starting driver...
2024-11-12T18:49:30.261Z DRIVER   opening serial port /dev/zwave
2024-11-12T18:49:30.263Z DRIVER   serial port opened
2024-11-12T18:49:30.264Z SERIAL » 0x15                                                                 (1 bytes)
2024-11-12T18:49:31.266Z DRIVER   loading configuration...
2024-11-12T18:49:31.269Z CONFIG   Using external configuration dir /usr/src/app/store/.config-db
2024-11-12T18:49:31.270Z CONFIG   version 14.3.1
2024-11-12T18:49:31.767Z DRIVER   beginning interview...
2024-11-12T18:49:31.768Z DRIVER   added request handler for AddNodeToNetwork (0x4a)...
                                  1 registered
2024-11-12T18:49:31.768Z DRIVER   added request handler for RemoveNodeFromNetwork (0x4b)...
                                  1 registered
2024-11-12T18:49:31.769Z DRIVER   added request handler for ReplaceFailedNode (0x63)...
                                  1 registered
2024-11-12T18:49:31.769Z DRIVER   added request handler for SetLearnMode (0x50)...
                                  1 registered
2024-11-12T18:49:31.769Z CNTRLR   querying Serial API capabilities...
2024-11-12T18:49:31.772Z SERIAL » 0x01030007fb                                                         (5 bytes)
2024-11-12T18:49:31.773Z DRIVER » [REQ] [GetSerialApiCapabilities]
2024-11-12T18:49:32.777Z CNTRLR   Failed to execute controller command after 1/3 attempts. Scheduling next try i
                                  n 100 ms.
2024-11-12T18:49:32.879Z DRIVER » [REQ] [GetSerialApiCapabilities]
2024-11-12T18:49:32.881Z SERIAL » 0x01030007fb                                                         (5 bytes)
2024-11-12T18:49:33.883Z CNTRLR   Failed to execute controller command after 2/3 attempts. Scheduling next try i
                                  n 1100 ms.
2024-11-12T18:49:34.985Z DRIVER » [REQ] [GetSerialApiCapabilities]
2024-11-12T18:49:34.987Z SERIAL » 0x01030007fb                                                         (5 bytes)
2024-11-12T18:49:35.991Z DRIVER   Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK 
                                  from the controller (ZW0200)
                                      at Driver.sendMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/D
                                  river.ts:6071:23)
                                      at ZWaveController2.queryCapabilities (/usr/src/app/node_modules/zwave-js/
                                  src/lib/controller/Controller.ts:1144:37)
                                      at Driver.initializeControllerAndNodes (/usr/src/app/node_modules/zwave-js
                                  /src/lib/driver/Driver.ts:1677:46)
                                      at Immediate.<anonymous> (/usr/src/app/node_modules/zwave-js/src/lib/drive
                                  r/Driver.ts:1478:16)
2024-11-12T18:49:35.993Z DRIVER   destroying driver instance...
2024-11-12T18:49:35.994Z DRIVER   all queues idle
2024-11-12T18:49:36.028Z DRIVER   driver instance destroyed
```

**Comment by pfgcoder** [comment]
I get the same error on 9.27:

```
2024-11-12T18:59:29.266Z DRIVER   Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK
                                  from the controller (ZW0200)
                                      at Driver.sendMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/D
                                  river.ts:6071:23)
                                      at ZWaveController2.queryCapabilities (/usr/src/app/node_modules/zwave-js/
                                  src/lib/controller/Controller.ts:1144:37)
                                      at Driver.initializeControllerAndNodes (/usr/src/app/node_modules/zwave-js
                                  /src/lib/driver/Driver.ts:1677:46)
                                      at Immediate.<anonymous> (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:1478:16)
2024-11-12T18:59:29.268Z DRIVER   destroying driver instance...
```

But it goes away and things work as expected when I go back to 9.26

**Comment by rwytrwal** [comment]
Same issue on USB STICK ZOOZ ZST10 S 700:
`2024-11-12T19:11:40.114Z DRIVER   Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK 
                                  from the controller (ZW0200)
                                      at Driver.sendMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/D
                                  river.ts:6071:23)
                                      at ZWaveController2.queryCapabilities (/usr/src/app/node_modules/zwave-js/
                                  src/lib/controller/Controller.ts:1144:37)
                                      at Driver.initializeControllerAndNodes (/usr/src/app/node_modules/zwave-js
                                  /src/lib/driver/Driver.ts:1677:46)
                                      at Immediate.<anonymous> (/usr/src/app/node_modules/zwave-js/src/lib/drive
                                  r/Driver.ts:1478:16)`

**Comment by icemarkom** [comment]
Same here, and I needed to roll-back to restore working ZWave at home.

This is what I have as the error message in the UI:

> Driver: Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK from the controller (ZW0200) at Driver.sendMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:6071:23) at ZWaveController2.queryCapabilities /usr/src/app/node_modules/zwave-js/src/lib/controller/Controller.ts: 1144:37) at Driver.initializeControllerAndNodes (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:1677:46) at Immediate.<anonymous> (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:1478:16) (ZWO100)
Error: Driver: Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK from the controller (ZW0200) at Driver.sendMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:6071:23) at ZWaveController2.queryCapabilities (/usr/src/app/node_modules/zwave js/src/lib/controller/Controller.ts:1144:37) at Driver.initializeControllerAndNodes (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:1677:46) at Immediate.<anonymous> (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:1478:16) (ZW0100)

**Comment by dobbsrx** [comment]
Same error here... reverted to zwave2mqtt:9.26.0 and my system is back up

**Comment by jerobins** [comment]
Also pulled sha256:6d36abbe92f950a6324cdfcc88e6a4fae7d08b91eca90454b5887c1885a399c2 since it was newer, did not work. Rolled back to 9.26.

**Comment by radhoo2k10** [comment]
Also rolled back to 9.26.

**Comment by chester512** [comment]
same, this update killed my system and have to rebuild.  using a nortek zwave stick.

**Comment by canedje** [comment]
Same for me. Same situation . Docker under Unraid. Rolled back to 9.26.0 up and running again

**Comment by sescandell** [comment]
Same here. Reverting to 9.26.0 and everything is working back as before. SiliconLab / Usb Controller / 700/800 Series : https://devices.zwave-js.io/?jumpTo=0x0000:0x0004:0x0004:0.0

**Comment by AlCalzone** [comment]
I **think** this should get fixed by https://github.com/zwave-js/zwave-js-ui/pull/4000 - at least I could access my stick in Docker on that branch.

**Comment by AlCalzone** [comment]
9.27.1 should fix this

**Comment by icemarkom** [comment]
Can confirm this fixed the problem on my end. Thank you.

**Comment by pfgcoder** [comment]
> 9.27.1 should fix this

Works for me, thanks for the quick turnaround

**Comment by sescandell** [comment]
> 9.27.1 should fix this

So fast,

Thanks for everything 🙇

**Comment by dobbsrx** [comment]
9.27.1 worked for me!

Thanks!
