### ISSUE TITLE
Cannot initialize controller, but I didn't make any changes, the /dev/serial/by-id shows the same path as before...

### ISSUE THREAD

**Issue by Majestic7979** [zwave-js/zwave-js-ui#4001]
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [ ] I have checked the troubleshooting section and my problem is not described there.
- [ ] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Z-Wave JS UI version

See bug description

### ZwaveJS version

See bug description

### Describe the bug

zwave-js-ui: 9.27.0.f3c4ac5
zwave-js: 14.3.1
home id: undefined
home hex: undefined

All was working at least until yesterday morning when I last used the door from outside, my door lock is z-wave, that's how I know it was fine at least up to yesterday. Today my housemate was locked out, door lock would not respond, I checked zwavejsui and it had this error:
```
Driver: Failed to initialize the driver: ZWaveError: Timeout while waiting for an ACK from the controller (ZW0200) at Driver.sendMessage (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:6071:23) at ZWaveController2.queryCapabilities (/usr/src/app/node_modules/zwave-js/src/lib/controller/Controller.ts:1144:37) at Driver.initializeControllerAndNodes (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:1677:46) at Immediate.<anonymous> (/usr/src/app/node_modules/zwave-js/src/lib/driver/Driver.ts:1478:16) (ZW0100)
```
I navigated to /dev/serial/by-id and the stick is recognized. I checked my docker CLI to ensure it was fine, and it was. I have my container auto-update itself via Watchtower, so the only thing that may have changed from yesterday to today is the zwavejsui version, and I believe this is the issue because upon logging in I received the usual "what's new" popup.

So whatever you did on the latest update as of this post, broke my Aeotec stick. When I say broke, don't worry I don't mean you killed it. I'm just saying it is not working. I will now try to use image tag to downgrade and see if it works again, will update this if it does. Otherwise please be aware it's non-functional and thankfully I was inside to open the door otherwise we'd have no way to get in and would have to break the door! So please treat this urgently as it may affect others, for instance it would be catastrophic if there was a fire and their lock was not operational because the latest update fubar'd something.

Thanks for reading my report, I appreciate your effort in making this software available!

### To Reproduce

Not applicable

### Expected behavior

Not break the driver...

**Comment by Majestic7979** [comment]
Update: I used image tag 9.26 and it works again, so definitely not an issue with my controller or setup, it's a problem in the latest images.

**Comment by thenoid** [comment]
https://github.com/zwave-js/zwave-js-ui/pull/4000

**Comment by wdenton2** [comment]
I am getting the exact same error. Restarting container, using different USB port, restarting the system - nothing fixes the error

**Comment by Hanzzie18** [comment]
also my Aeotec USB stick was recognized anymore. I did a restart of my docker, replugged the USB stick but nothing works. When I did recreate the image I've got everything back online. Not sure what the root cause was in my case.

**Comment by willheineman** [comment]
Same issue here using a HUSBZB-1 controller

**Comment by robertsLando** [comment]
Please make a [driver log](https://zwave-js.github.io/zwave-js-ui/#/troubleshooting/generating-logs?id=driver-logs), loglevel `debug` and attach it here as a file (drag & drop into the text field).

**Comment by robertsLando** [comment]
cc @AlCalzone seems this issue is still relevant with 9.27.1
